// Interaction refinements; viewing changes never rewrite a recording.
function polishLabel(node,zh,en){node.dataset.polishZh=zh;node.dataset.polishEn=en;node.textContent=E(zh,en);return node;}
window.addEventListener('wescreen-language',()=>{for(const n of document.querySelectorAll('[data-polish-zh]'))n.textContent=E(n.dataset.polishZh,n.dataset.polishEn);});
function polishButton(id,zh,en,fn,parent){const b=polishLabel(document.createElement('button'),zh,en);b.id=id;b.type='button';b.onclick=fn;parent.append(b);return b;}
// Transport icons and text tools use separate sizing rules.
function toolGroup(zh,en,nodes){const box=document.createElement('section');box.className='pro-tool-group';box.append(polishLabel(document.createElement('h4'),zh,en));const row=document.createElement('div');row.className='pro-tool-grid';for(const node of nodes.filter(Boolean))row.append(node);box.append(row);proPlayerTools.append(box);return row;}
toolGroup('逐帧与循环','Frames & loop',[$('player-frame-back'),$('player-frame-next'),frameLabel,$('player-loop-a'),$('player-loop-b'),$('player-loop-off')]);
toolGroup('章节与字幕','Chapters & subtitles',[$('player-bookmark'),bookmarks,subtitleLabel,$('player-subtitle-off'),subtitleOffset]);
toolGroup('声音与同步','Audio & sync',[audioLabel,delayLabel,$('player-audio-repair')]);
const playerMenus=()=>cinemaMenus.filter(m=>m.open);
function placePlayerMenus(){for(const menu of playerMenus()){const panel=menu.querySelector(':scope > .cinema-popover');if(!panel)continue;panel.style.transform='';panel.style.maxHeight='';const bounds=panel.getBoundingClientRect(),anchor=menu.querySelector('summary').getBoundingClientRect();const left=8,right=innerWidth-8,top=8;const dx=bounds.left<left?left-bounds.left:bounds.right>right?right-bounds.right:0;panel.style.transform=`translateX(${dx}px)`;panel.style.maxHeight=Math.max(100,Math.min(620,anchor.top-top-16))+'px';}}
for(const menu of cinemaMenus)menu.addEventListener('toggle',()=>{placePlayerMenus();revealFullscreenControls();});
window.addEventListener('resize',placePlayerMenus);document.addEventListener('fullscreenchange',()=>requestAnimationFrame(placePlayerMenus));
$('playback-shell').addEventListener('focusin',revealFullscreenControls);
document.addEventListener('pointerdown',event=>{if(!event.target.closest('.cinema-menu'))for(const m of cinemaMenus)m.open=false;});
$('playback-shell').addEventListener('keydown',event=>{if(event.key==='Escape' && playerMenus().length){event.stopPropagation();event.preventDefault();const last=playerMenus().at(-1);last.open=false;last.querySelector('summary').focus();}});

// Hold-to-compare hides viewing enhancement without resetting settings or the media clock.
const compareButton=polishButton('player-compare','按住看原画','Hold to view original',()=>{},qualityPanel);
let originalCompare=false;
function setOriginalCompare(on){originalCompare=on;$('playback-shell').classList.toggle('compare-original',on);compareButton.setAttribute('aria-pressed',String(on));revealFullscreenControls();}
compareButton.onpointerdown=event=>{event.preventDefault();compareButton.setPointerCapture(event.pointerId);setOriginalCompare(true);};
for(const event of ['pointerup','pointercancel','lostpointercapture'])compareButton.addEventListener(event,()=>setOriginalCompare(false));
compareButton.addEventListener('keydown',event=>{if([' ','Enter'].includes(event.key)){event.preventDefault();setOriginalCompare(true);}});
compareButton.addEventListener('keyup',event=>{if([' ','Enter'].includes(event.key))setOriginalCompare(false);});compareButton.addEventListener('blur',()=>setOriginalCompare(false));window.addEventListener('blur',()=>setOriginalCompare(false));

// Subtitle appearance is independent of the input file and follows all parts.
const subtitleStyle=document.createElement('div');subtitleStyle.className='subtitle-style';
const subtitleFont=proControl('player-subtitle-font','字幕字号（px）','Subtitle size (px)','range','24','14','48','1');
const subtitlePosition=proControl('player-subtitle-position','字幕位置（距顶部 %）','Subtitle position (% from top)','range','82','15','90','1');
polishLabel(subtitleFont.querySelector('span'),'字幕字号（px）','Subtitle size (px)');polishLabel(subtitlePosition.querySelector('span'),'字幕位置（距顶部 %）','Subtitle position (% from top)');
subtitleStyle.append(subtitleFont,subtitlePosition);subtitleLabel.after(subtitleStyle);
function applySubtitleAppearance(){const size=Number($('player-subtitle-font').value)||24,line=Number($('player-subtitle-position').value)||82;$('playback-shell').style.setProperty('--subtitle-size',size+'px');for(const cue of playerSubtitleTrack?.track.cues||[]){cue.snapToLines=false;cue.line=line;}}
const originalProjectCues=projectSubtitleCues;projectSubtitleCues=()=>{originalProjectCues();applySubtitleAppearance();};
for(const id of ['player-subtitle-font','player-subtitle-position'])$(id).oninput=()=>{applySubtitleAppearance();savePlayerDefaults();};

// A separate audio clock allows both earlier and later audio, including crossing a part boundary.
const syncAudio=document.createElement('audio');syncAudio.preload='auto';syncAudio.preservesPitch=true;syncAudio.hidden=true;document.body.append(syncAudio);
let syncAudioUrl=null,syncAudioKey=null,syncGeneration=0,syncBusy=false,playerAudioTimer=null,syncVideoWaiting=false;
function rampAudio(param,value,seconds=.025){const t=playerAudioContext.currentTime;param.cancelScheduledValues(t);param.setValueAtTime(param.value,t);param.linearRampToValueAtTime(value,t+seconds);}
setPlayerAudio=async function(mode){const v=$('preview');if(!playerAudioContext){playerAudioContext=new AudioContext();const source=playerAudioContext.createMediaElementSource(v),aux=playerAudioContext.createMediaElementSource(syncAudio),primaryGain=playerAudioContext.createGain(),auxGain=playerAudioContext.createGain(),filter=playerAudioContext.createBiquadFilter(),compressor=playerAudioContext.createDynamicsCompressor(),gain=playerAudioContext.createGain(),delay=playerAudioContext.createDelay(2),gate=playerAudioContext.createGain();source.connect(primaryGain).connect(filter);aux.connect(auxGain).connect(filter);filter.connect(compressor).connect(gain).connect(delay).connect(gate).connect(playerAudioContext.destination);auxGain.gain.value=0;playerAudioGraph={filter,compressor,gain,delay,gate,primaryGain,auxGain};}await playerAudioContext.resume();const g=playerAudioGraph;g.filter.type=mode==='voice'?'peaking':'allpass';g.filter.frequency.value=2200;g.filter.Q.value=.8;g.filter.gain.value=mode==='voice'?4:0;g.compressor.threshold.value=mode==='night'?-28:mode==='level'?-20:0;g.compressor.knee.value=mode==='original'?0:20;g.compressor.ratio.value=mode==='original'?1:mode==='night'?8:3;g.compressor.attack.value=.01;g.compressor.release.value=.2;rampAudio(g.gain.gain,mode==='level'?1.15:1);g.delay.delayTime.value=0;rampAudio(g.primaryGain.gain,playerSyncDelay===0?1:0);rampAudio(g.auxGain.gain,playerSyncDelay===0?0:1);if(playerSyncDelay===0){syncAudio.pause();rampAudio(g.gate.gain,v.paused?0:1);}else await syncPlayerAudio(true);};
async function syncPlayerAudio(force=false){if(!playerAudioGraph || !playerSyncDelay || syncBusy)return;const v=$('preview'),target=playbackTimelineTime()-playerSyncDelay,total=playbackTimelineTotal();if(target<0 || target>=total || v.paused || v.seeking || syncVideoWaiting || v.readyState<3){syncAudio.pause();rampAudio(playerAudioGraph.gate.gain,0);return;}let index=0,offset=0;while(index<playbackParts.length-1 && target>=offset+(playbackParts[index].duration||0)/1000){offset+=(playbackParts[index].duration||0)/1000;index++;}const part=playbackParts[index],key=part?.id || v.currentSrc,generation=syncGeneration;syncBusy=true;try{if(syncAudioKey!==key){rampAudio(playerAudioGraph.gate.gain,0);const blob=part?await readStore('videos',part.id):null;if(generation!==syncGeneration)return;syncAudio.pause();if(syncAudioUrl)URL.revokeObjectURL(syncAudioUrl);syncAudioUrl=blob?URL.createObjectURL(blob):null;syncAudioKey=key;syncAudio.src=syncAudioUrl || v.currentSrc;await new Promise((resolve,reject)=>{const done=()=>{cleanup();resolve();},fail=()=>{cleanup();reject(new Error(E('音轨读取失败，已恢复原声。','Audio loading failed; original audio restored.')));},timer=setTimeout(fail,8000),cleanup=()=>{clearTimeout(timer);syncAudio.removeEventListener('loadedmetadata',done);syncAudio.removeEventListener('error',fail);};syncAudio.addEventListener('loadedmetadata',done,{once:true});syncAudio.addEventListener('error',fail,{once:true});syncAudio.load();});}if(generation!==syncGeneration)return;syncAudio.volume=v.volume;syncAudio.muted=v.muted;syncAudio.playbackRate=v.playbackRate;const at=Math.max(0,Math.min(syncAudio.duration-.01,playbackTimelineTime()-playerSyncDelay-offset));if(force || Math.abs(syncAudio.currentTime-at)>.12)syncAudio.currentTime=at;if(!v.paused&&!v.seeking&&!syncVideoWaiting&&v.readyState>=3){await syncAudio.play();if(generation===syncGeneration&&!v.paused&&!v.seeking&&!syncVideoWaiting)rampAudio(playerAudioGraph.gate.gain,1);else syncAudio.pause();}}catch(error){playerSyncDelay=0;$('player-audio-delay').value='0';rampAudio(playerAudioGraph.primaryGain.gain,1);rampAudio(playerAudioGraph.auxGain.gain,0);rampAudio(playerAudioGraph.gate.gain,v.paused?0:1);playerStatus(error.message,error.message);}finally{syncBusy=false;}}
polishLabel(delayLabel.querySelector('span'),'音画同步（秒：负值提前，正值延后）','Audio sync (seconds: negative earlier, positive later)');
const syncInput=$('player-audio-delay');syncInput.min='-2';syncInput.max='2';syncInput.step='.05';
syncInput.onchange=async()=>{playerSyncDelay=Math.max(-2,Math.min(2,Number(syncInput.value)||0));syncInput.value=String(playerSyncDelay);syncGeneration++;syncAudio.pause();syncAudioKey=null;await setPlayerAudio(audioSelect.value);savePlayerDefaults();};
const syncButtons=document.createElement('div');syncButtons.className='pro-tool-grid';delayLabel.after(syncButtons);
for(const [id,zh,en,delta] of [['sync-earlier','提前 50 ms','Earlier 50 ms',-.05],['sync-later','延后 50 ms','Later 50 ms',.05],['sync-reset','同步归零','Reset sync',null]])polishButton(id,zh,en,()=>{syncInput.value=String(delta===null?0:Math.round((playerSyncDelay+delta)*100)/100);syncInput.dispatchEvent(new Event('change'));},syncButtons);
for(const event of ['play','playing'])$('preview').addEventListener(event,()=>{if(event==='playing'||$('preview').readyState>=3)syncVideoWaiting=false;if(playerAudioContext){playerAudioContext.resume().catch(()=>{});if(!playerSyncDelay)rampAudio(playerAudioGraph.gate.gain,1);else syncPlayerAudio(true);}});
for(const event of ['pause','seeking','emptied','waiting'])$('preview').addEventListener(event,()=>{if(event!=='pause')syncVideoWaiting=true;syncAudio.pause();if(playerAudioGraph)rampAudio(playerAudioGraph.gate.gain,0);});
for(const event of ['seeked','ratechange','volumechange'])$('preview').addEventListener(event,()=>{if(event==='seeked'&&$('preview').readyState>=3)syncVideoWaiting=false;if(playerSyncDelay)syncPlayerAudio(true);else if(playerAudioGraph&&!$('preview').paused)rampAudio(playerAudioGraph.gate.gain,1);});
playerAudioTimer=setInterval(()=>{if(playerSyncDelay&&!$('preview').paused)syncPlayerAudio();},100);
window.addEventListener('pagehide',()=>{clearInterval(playerAudioTimer);syncGeneration++;syncAudio.pause();if(syncAudioUrl)URL.revokeObjectURL(syncAudioUrl);});

// Global defaults for new videos; per-video saved settings still take precedence.
async function savePlayerDefaults(){await runTx('meta','readwrite',tx=>tx.objectStore('meta').put({volume:$('preview').volume,mode:audioSelect.value,sync:playerSyncDelay,font:Number($('player-subtitle-font').value),position:Number($('player-subtitle-position').value)},'player-defaults')).catch(()=>{});}
$('preview').addEventListener('volumechange',savePlayerDefaults);audioSelect.addEventListener('change',savePlayerDefaults);
window.addEventListener('DOMContentLoaded',async()=>{const value=await readStore('meta','player-defaults');if(!value)return;$('preview').volume=value.volume??1;audioSelect.value=value.mode||'original';playerSyncDelay=value.sync||0;syncInput.value=String(playerSyncDelay);$('player-subtitle-font').value=String(value.font||24);$('player-subtitle-position').value=String(value.position||82);applySubtitleAppearance();});
$('preview').addEventListener('loadedmetadata',async()=>{const v=$('preview');if(audioSelect.value!=='original'||playerSyncDelay||playerAudioContext)await setPlayerAudio(audioSelect.value);applySubtitleAppearance();});

// Immediate, accessible recovery feedback. Originals remain recoverable on failure.
const recoveryProgress=document.createElement('progress');recoveryProgress.id='recovery-progress';recoveryProgress.hidden=true;recoveryProgress.max=1;const recoveryStatus=document.createElement('p');recoveryStatus.id='recovery-status';recoveryStatus.setAttribute('role','status');$('recovery').append(recoveryProgress,recoveryStatus);
const recoverOriginal=handleRecovery;handleRecovery=async function(keep){if($('recover').disabled)return;recoveryProgress.hidden=false;recoveryProgress.removeAttribute('value');polishLabel(recoveryStatus,keep?'正在检查并恢复到录像库…':'正在清理恢复片段…',keep?'Checking and restoring to the library…':'Clearing recovery fragments…');try{await recoverOriginal(keep);const remaining=await pendingSessions();recoveryProgress.value=remaining.length?0:1;polishLabel(recoveryStatus,remaining.length?'仍有待恢复片段，请检查提示后重试。':keep?'已恢复到录像库，原片段已安全入库。':'已清理恢复片段。',remaining.length?'Recovery fragments remain. Check the notice and retry.':keep?'Restored safely to the library.':'Recovery fragments cleared.');}finally{recoveryProgress.hidden=true;}};
function updateRecoveryProgress(done,total){recoveryProgress.max=Math.max(1,total);recoveryProgress.value=done;recoveryStatus.textContent=E('恢复进度：','Recovery: ')+done+' / '+total;}
