// Optional local interface lock. Video bytes remain unchanged and are not encrypted.
const privacy = (() => {
  let config=null, unlocked=false, pending=null, resolvePending=null, mode='unlock', failures=0, retryAt=0;
  const channel=new BroadcastChannel('wescreen-privacy');
  const dialog=document.createElement('dialog');dialog.id='privacy-dialog';
  dialog.innerHTML='<form id="privacy-form"><div class="privacy-icon" aria-hidden="true">◇</div><h2 id="privacy-title"></h2><p id="privacy-hint" class="hint"></p><label id="privacy-old-label"><span></span><input id="privacy-old" type="password" autocomplete="current-password" maxlength="256"></label><label><span id="privacy-password-label"></span><input id="privacy-password" type="password" autocomplete="current-password" maxlength="256" required></label><label id="privacy-confirm-label"><span></span><input id="privacy-confirm" type="password" autocomplete="new-password" maxlength="256"></label><p id="privacy-error" role="alert"></p><div class="controls"><button id="privacy-cancel" type="button" class="quiet"></button><button id="privacy-submit" type="submit" class="primary"></button></div></form>';
  document.body.append(dialog);
  const card=document.createElement('section');card.className='privacy-card';card.innerHTML='<div><h3 id="privacy-settings-title"></h3><p id="privacy-settings-hint" class="hint"></p><p id="privacy-setting-status"></p></div><div class="controls"><button id="privacy-configure" class="quiet"></button><button id="privacy-disable" class="quiet"></button><button id="privacy-lock" class="quiet"></button></div>';$('about-view').append(card);
  const quick=document.createElement('button');quick.id='privacy-quick-lock';quick.className='quiet';quick.type='button';document.querySelector('.header-actions').append(quick);
  function refresh(){
    $('privacy-settings-title').textContent=E('隐私密码','Privacy password');$('privacy-settings-hint').textContent=E('保护录像库和播放器入口。仅为界面访问锁，不加密视频；忘记密码无法在这里找回。','Protect library and player access. Interface lock only; videos are not encrypted. Forgotten passwords cannot be recovered here.');$('privacy-setting-status').textContent=config?E('已开启 · 关闭页面或立即锁定后需重新输入','Enabled · unlock again after closing this page or locking'):E('未开启','Not enabled');
    quick.textContent=E('锁定','Lock');quick.hidden=!config;
    $('privacy-configure').textContent=config?E('修改密码','Change password'):E('设置密码','Set password');$('privacy-disable').textContent=E('关闭保护','Disable protection');$('privacy-disable').hidden=!config;$('privacy-lock').textContent=E('立即锁定','Lock now');$('privacy-lock').hidden=!config;
  }
  const ready=readStore('meta','privacy-password').then(value=>{config=value||null;refresh();});
  const encode=bytes=>btoa(String.fromCharCode(...bytes));
  async function derive(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return encode(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:Uint8Array.from(atob(salt),c=>c.charCodeAt(0)),iterations:310000},key,256)));}
  async function verify(password){const value=await derive(password,config.salt);let difference=value.length^config.verifier.length;for(let i=0;i<value.length;i++)difference|=value.charCodeAt(i)^config.verifier.charCodeAt(i);return difference===0;}
  function finish(value){dialog.close();$('privacy-form').reset();const resolve=resolvePending;pending=null;resolvePending=null;resolve?.(value);}
  function prompt(next){if(pending)return pending;mode=next;pending=new Promise(resolve=>resolvePending=resolve);$('privacy-form').reset();$('privacy-error').textContent='';const setting=mode==='setup'||mode==='change';$('privacy-title').textContent=setting?E('设置隐私密码','Set privacy password'):mode==='remove'?E('关闭隐私保护','Disable privacy protection'):E('解锁私人空间','Unlock private space');$('privacy-hint').textContent=setting?E('至少 8 个字符。本次页面解锁有效，关闭后需重新输入。','At least 8 characters. Unlock lasts for this page; closing it locks access.'):E('请输入已设定的密码。取消不会删除任何录像。','Enter your password. Cancelling keeps all recordings.');$('privacy-old-label').hidden=mode!=='change';$('privacy-old-label span').textContent=E('当前密码','Current password');$('privacy-old').required=mode==='change';$('privacy-password-label').textContent=setting?E('新密码','New password'):E('密码','Password');$('privacy-password').autocomplete=setting?'new-password':'current-password';$('privacy-confirm-label').hidden=!setting;$('privacy-confirm-label span').textContent=E('确认新密码','Confirm new password');$('privacy-confirm').required=setting;$('privacy-cancel').textContent=E('取消','Cancel');$('privacy-submit').textContent=setting?E('保存密码','Save password'):mode==='remove'?E('确认关闭','Disable'):E('解锁','Unlock');dialog.showModal();$('privacy-password').focus();return pending;}
  async function request(){await ready;return !config||unlocked||await prompt('unlock');}
  function lock(){if(!config)return;unlocked=false;$('preview').pause();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});if(document.pictureInPictureElement)document.exitPictureInPicture().catch(()=>{});if(document.body.classList.contains('cinema-mode'))setTheatreMode(false);if(!recorder || recorder.state==='inactive')recordingView='setup';navigateWorkspace('capture');refresh();}
  $('privacy-form').onsubmit=async event=>{event.preventDefault();const button=$('privacy-submit');button.disabled=true;try{if(Date.now()<retryAt)throw new Error(E('尝试过多，请稍后再试。','Too many attempts. Try again shortly.'));const password=$('privacy-password').value;if(config && !await verify(mode==='change'?$('privacy-old').value:password)){failures++;if(failures>=5)retryAt=Date.now()+30000;throw new Error(E('密码不正确。','Incorrect password.'));}if(mode==='setup'||mode==='change'){if(password.length<8)throw new Error(E('密码至少 8 个字符。','Use at least 8 characters.'));if(password!==$('privacy-confirm').value)throw new Error(E('两次密码不一致。','Passwords do not match.'));const salt=encode(crypto.getRandomValues(new Uint8Array(16)));const next={salt,verifier:await derive(password,salt),algorithm:'PBKDF2-SHA256',iterations:310000};await runTx('meta','readwrite',tx=>tx.objectStore('meta').put(next,'privacy-password'));config=next;channel.postMessage('changed');}else if(mode==='remove'){await runTx('meta','readwrite',tx=>tx.objectStore('meta').delete('privacy-password'));config=null;channel.postMessage('changed');}unlocked=true;failures=0;retryAt=0;refresh();finish(true);}catch(error){$('privacy-error').textContent=error.message;}finally{button.disabled=false;}};
  $('privacy-cancel').onclick=()=>finish(false);dialog.addEventListener('cancel',event=>{event.preventDefault();finish(false);});
  $('privacy-configure').onclick=async()=>{await ready;prompt(config?'change':'setup');};$('privacy-disable').onclick=()=>prompt('remove');$('privacy-lock').onclick=()=>{lock();channel.postMessage('lock');};
  quick.onclick=()=>{lock();channel.postMessage('lock');};
  channel.onmessage=async event=>{if(event.data==='changed'){config=await readStore('meta','privacy-password');refresh();}lock();};
  $('preview').addEventListener('play',()=>{if(config&&!unlocked)$('preview').pause();});
  window.addEventListener('wescreen-language',refresh);
  return {ready,request,canAccess:()=>!config||unlocked,lock};
})();
