// Viewing tools live inside the player's existing menus.
let playerAudioContext=null,playerAudioGraph=null,playerLoop={a:null,b:null,enabled:false},playerBookmarks=[],playerSubtitleUrl=null,playerSubtitleTrack=null,playerFrameRate=30,playerScrubPlaying=false,playerLastDeleted=[],playerSyncDelay=0;
const proPlayerMenu=document.createElement('details');proPlayerMenu.className='advanced';proPlayerMenu.id='player-pro-tools';const proPlayerTitle=document.createElement('summary');proPlayerTitle.textContent=E('专业播放工具','Professional playback tools');proPlayerMenu.append(proPlayerTitle);const proPlayerTools=document.createElement('div');proPlayerTools.className='pro-player-tools';proPlayerMenu.append(proPlayerTools);
const playerMore=$('playback-more-menu');(playerMore?.querySelector('.cinema-popover') || rotationMenu.querySelector('.playback-toolbar')).append(proPlayerMenu);
function playerAction(id,zh,en,action){const button=document.createElement('button');button.type='button';button.id=id;button.textContent=E(zh,en);button.onclick=async()=>{if(button.disabled)return;button.disabled=true;try{await action();}catch(error){$('playback-status').textContent=error.message;}finally{button.disabled=false;}};proPlayerTools.append(button);return button;}
function playerStatus(zh,en){$('playback-status').textContent=E(zh,en);}
playerAction('player-frame-back','上一帧','Previous frame',()=>{$('preview').pause();return seekRecordingTimeline(playbackTimelineTime()-1/playerFrameRate,false);});
playerAction('player-frame-next','下一帧','Next frame',()=>{$('preview').pause();return seekRecordingTimeline(playbackTimelineTime()+1/playerFrameRate,false);});
const frameLabel=document.createElement('label');frameLabel.textContent=E('逐帧步长（fps）','Frame step (fps)');const frameRate=document.createElement('input');frameRate.type='number';frameRate.min='1';frameRate.max='120';frameRate.value='30';frameRate.onchange=()=>{playerFrameRate=Math.max(1,Math.min(120,Number(frameRate.value)||30));};frameLabel.append(frameRate);proPlayerTools.append(frameLabel);
playerAction('player-loop-a','设为循环起点 A','Set loop A',()=>{playerLoop.a=playbackTimelineTime();playerStatus('已标记 A 点','Loop A marked');});
playerAction('player-loop-b','设为循环终点 B','Set loop B',()=>{const b=playbackTimelineTime();if(playerLoop.a===null || b<=playerLoop.a+.1)throw new Error(E('先设置较早的 A 点。','Set an earlier A point first.'));playerLoop.b=b;playerLoop.enabled=true;playerStatus('A/B 循环已开启','A/B loop enabled');});
playerAction('player-loop-off','关闭循环','Disable loop',()=>{playerLoop.enabled=false;playerStatus('循环已关闭','Loop disabled');});
$('preview').addEventListener('timeupdate',()=>{if(playerLoop.enabled && playbackTimelineTime()>=playerLoop.b)seekRecordingTimeline(playerLoop.a,true).catch(error=>setNotice(error.message));});
function playbackProjectId(){return playbackParts[0]?.recordingGroupId || playbackParts[0]?.id || activePlaybackId;}
async function savePlayerBookmarks(){const id=playbackProjectId();if(id)await runTx('meta','readwrite',tx=>tx.objectStore('meta').put(playerBookmarks,'bookmarks:'+id));renderPlayerBookmarks();}
const bookmarks=document.createElement('div');bookmarks.className='player-bookmarks';proPlayerTools.append(bookmarks);
function renderPlayerBookmarks(){bookmarks.replaceChildren();for(const mark of playerBookmarks){const line=document.createElement('div');line.className='controls';const jump=document.createElement('button');jump.type='button';jump.textContent=fmt(mark.time*1000)+' · '+mark.name;jump.onclick=()=>seekRecordingTimeline(mark.time).catch(error=>setNotice(error.message));const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',E('删除书签','Delete bookmark'));remove.onclick=async()=>{playerBookmarks=playerBookmarks.filter(m=>m.id!==mark.id);await savePlayerBookmarks();};line.append(jump,remove);bookmarks.append(line);}}
playerAction('player-bookmark','添加书签 / 章节','Add bookmark / chapter',async()=>{const name=prompt(E('书签名称','Bookmark name'),fmt(playbackTimelineTime()*1000));if(!name)return;playerBookmarks.push({id:crypto.randomUUID(),time:playbackTimelineTime(),name:name.trim().slice(0,120)});playerBookmarks.sort((a,b)=>a.time-b.time);await savePlayerBookmarks();});
const subtitleLabel=document.createElement('label');subtitleLabel.textContent=E('加载本地字幕（SRT / VTT）','Load subtitles (SRT / VTT)');const subtitleInput=document.createElement('input');subtitleInput.type='file';subtitleInput.accept='.srt,.vtt';subtitleInput.id='player-subtitle';subtitleLabel.append(subtitleInput);proPlayerTools.append(subtitleLabel);
function srtToVtt(text){const clean=text.replace(/^\uFEFF/,'');if(/^WEBVTT/.test(clean))return clean;return 'WEBVTT\n\n'+clean.replace(/(\d{2}:\d{2}:\d{2}),(\d{3})/g,'$1.$2');}
function projectSubtitleCues(){if(!playerSubtitleTrack)return;const track=playerSubtitleTrack.track,offset=playbackParts.slice(0,playbackPartIndex).reduce((sum,p)=>sum+(p.duration||0)/1000,0);for(const cue of [...(track.cues||[])])track.removeCue(cue);for(const cue of playerSubtitleCues){const start=cue.start+subtitlePreviousOffset-offset,end=cue.end+subtitlePreviousOffset-offset;if(end>0 && start<$('preview').duration){const projected=new VTTCue(Math.max(0,start),Math.max(.01,end),cue.text);projected.line=cue.line;projected.align=cue.align;track.addCue(projected);}}}
subtitleInput.onchange=async()=>{const file=subtitleInput.files[0];if(!file)return;if(file.size>5*1024*1024)return playerStatus('字幕超过 5 MB','Subtitle exceeds 5 MB');if(playerSubtitleUrl)URL.revokeObjectURL(playerSubtitleUrl);playerSubtitleTrack?.remove();playerSubtitleCues=[];playerSubtitleUrl=URL.createObjectURL(new Blob([srtToVtt(await file.text())],{type:'text/vtt'}));playerSubtitleTrack=document.createElement('track');playerSubtitleTrack.kind='subtitles';playerSubtitleTrack.label=file.name;playerSubtitleTrack.src=playerSubtitleUrl;playerSubtitleTrack.default=true;playerSubtitleTrack.onload=()=>{playerSubtitleCues=[...(playerSubtitleTrack.track.cues||[])].map(c=>({start:c.startTime,end:c.endTime,text:c.text,line:c.line,align:c.align}));projectSubtitleCues();};$('preview').append(playerSubtitleTrack);playerSubtitleTrack.track.mode='showing';};
playerAction('player-subtitle-off','隐藏字幕','Hide subtitles',()=>{if(playerSubtitleTrack)playerSubtitleTrack.track.mode=playerSubtitleTrack.track.mode==='showing'?'hidden':'showing';});
const subtitleOffset=proControl('player-subtitle-offset','字幕偏移（秒，正值延后）','Subtitle delay (seconds)','number','0');subtitleOffset.querySelector('input').step='.1';proPlayerTools.append(subtitleOffset);let subtitlePreviousOffset=0,playerSubtitleCues=[];subtitleOffset.querySelector('input').onchange=()=>{subtitlePreviousOffset=Math.max(-60,Math.min(60,Number($('player-subtitle-offset').value)||0));projectSubtitleCues();};
async function setPlayerAudio(mode){const v=$('preview');if(!playerAudioContext){playerAudioContext=new AudioContext();const source=playerAudioContext.createMediaElementSource(v),filter=playerAudioContext.createBiquadFilter(),compressor=playerAudioContext.createDynamicsCompressor(),gain=playerAudioContext.createGain(),delay=playerAudioContext.createDelay(2);source.connect(filter).connect(compressor).connect(gain).connect(delay).connect(playerAudioContext.destination);playerAudioGraph={filter,compressor,gain,delay};}await playerAudioContext.resume();const {filter,compressor,gain,delay}=playerAudioGraph;filter.type=mode==='voice'?'peaking':'allpass';filter.frequency.value=2200;filter.Q.value=.8;filter.gain.value=mode==='voice'?4:0;compressor.threshold.value=mode==='night'?-28:mode==='level'?-20:0;compressor.knee.value=mode==='original'?0:20;compressor.ratio.value=mode==='original'?1:mode==='night'?8:3;compressor.attack.value=.01;compressor.release.value=.2;gain.gain.value=mode==='level'?1.3:1;delay.delayTime.value=playerSyncDelay;}
const audioLabel=document.createElement('label');audioLabel.textContent=E('播放声音','Playback audio');const audioSelect=document.createElement('select');audioSelect.id='player-audio-mode';for(const [value,zh,en] of [['original','原声','Original'],['voice','人声清晰','Clear voice'],['night','夜间模式','Night mode'],['level','音量均衡','Volume leveling']]){const option=document.createElement('option');option.value=value;option.textContent=E(zh,en);audioSelect.append(option);}audioSelect.onchange=()=>setPlayerAudio(audioSelect.value).catch(error=>setNotice(error.message));audioLabel.append(audioSelect);proPlayerTools.append(audioLabel);
const delayLabel=proControl('player-audio-delay','音频延后（秒，0–2）','Audio delay (0–2 seconds)','number','0');delayLabel.querySelector('input').step='.05';delayLabel.querySelector('input').min='0';delayLabel.querySelector('input').max='2';delayLabel.querySelector('input').onchange=async()=>{playerSyncDelay=Math.max(0,Math.min(2,Number($('player-audio-delay').value)||0));await setPlayerAudio(audioSelect.value);};proPlayerTools.append(delayLabel);
$('preview').preservesPitch=true;
// Scrub pauses decoding while the pointer is down and resumes on release.
let currentPlayerProject=null;
$('preview').addEventListener('loadedmetadata',async()=>{const source=playbackParts[playbackPartIndex];playerFrameRate=source?.frameRate || 30;frameRate.value=String(playerFrameRate);const project=playbackProjectId();if(project===currentPlayerProject){projectSubtitleCues();return;}currentPlayerProject=project;playerLoop={a:null,b:null,enabled:false};const saved=await readStore('meta','bookmarks:'+project)||[];if(currentPlayerProject!==project)return;playerBookmarks=saved;renderPlayerBookmarks();if(playerSubtitleTrack){playerSubtitleTrack.remove();playerSubtitleTrack=null;}if(playerSubtitleUrl){URL.revokeObjectURL(playerSubtitleUrl);playerSubtitleUrl=null;}playerSubtitleCues=[];subtitlePreviousOffset=0;$('player-subtitle-offset').value='0';});
// Small, reversible library operations.
const libraryPro=document.createElement('details');libraryPro.className='advanced';const libraryProTitle=document.createElement('summary');libraryProTitle.textContent=E('文件管理','File management');libraryPro.append(libraryProTitle);$('recording-library').append(libraryPro);
function libraryAction(id,zh,en,fn){const b=document.createElement('button');b.type='button';b.id=id;b.textContent=E(zh,en);b.onclick=async()=>{if(b.disabled)return;b.disabled=true;try{await fn();}catch(error){$('library-status').textContent=error.message;}finally{b.disabled=false;}};libraryPro.append(b);return b;}
libraryAction('library-undo','撤销最近删除','Undo last deletion',async()=>{for(const entry of playerLastDeleted)await updateRecording(entry.id,{deletedAt:entry.deletedAt||null});playerLastDeleted=[];await renderRecordingLibrary();});
libraryAction('library-batch-rename','批量重命名','Batch rename',async()=>{if(!librarySelection.size)throw new Error(E('先选择录像','Select recordings first'));const prefix=prompt(E('统一名称前缀（自动编号）','Name prefix (automatically numbered)'));if(!prefix?.trim())return;let index=1;for(const id of librarySelection){const entry=await readStore('recordings',id);if(!entry)continue;const groups=recordingGroups(await readStore('recordings')),parts=groups.find(e=>e.id===id)?._parts||[entry];for(const [part,e] of parts.entries())await updateRecording(e.id,{name:prefix.trim().replace(/[\\/:*?"<>|]/g,'-').slice(0,100)+'-'+String(index).padStart(3,'0')+(parts.length>1?'-part-'+String(part+1).padStart(3,'0'):'')+(e.name.endsWith('.mp4')?'.mp4':'.webm')});index++;}await renderRecordingLibrary();});
libraryAction('library-audio-files','下载独立录音','Download separate audio',async()=>{const all=await readStore('meta');const audio=all.filter(e=>e?.audioOnly);if(!audio.length)throw new Error(E('没有独立录音；录前启用独立音轨。','No separate audio; enable it before recording.'));const dialog=document.createElement('dialog');const title=document.createElement('h2');title.textContent=E('独立录音','Separate audio');dialog.append(title);for(const entry of audio){const line=document.createElement('div');line.className='controls';const b=document.createElement('button');b.type='button';b.textContent=entry.name;b.onclick=async()=>{try{await download(new Blob(await loadChunks(entry.session),{type:entry.mimeType}),entry.name,null);}catch(error){$('library-status').textContent=error.message;}};const remove=document.createElement('button');remove.type='button';remove.textContent=E('删除独立录音','Delete separate audio');remove.onclick=async()=>{try{await discardSession(entry.session);await runTx('meta','readwrite',tx=>tx.objectStore('meta').delete('audio:'+entry.session));line.remove();}catch(error){$('library-status').textContent=error.message;}};line.append(b,remove);dialog.append(line);}const close=document.createElement('button');close.textContent=E('关闭','Close');close.onclick=()=>{dialog.close();dialog.remove();};dialog.append(close);document.body.append(dialog);dialog.showModal();});
libraryAction('library-relink','重新关联磁盘文件','Relink disk file',async()=>{if(librarySelection.size!==1)throw new Error(E('请选择一条录像','Select one recording'));const [handle]=await showOpenFilePicker({types:[{description:'Video',accept:{'video/mp4':['.mp4'],'video/webm':['.webm']}}]});const entry=await readStore('recordings',[...librarySelection][0]),file=await handle.getFile();const original=await readStore('videos',entry.id);async function fingerprint(blob){const head=await blob.slice(0,65536).arrayBuffer(),tail=await blob.slice(Math.max(0,blob.size-65536)).arrayBuffer();return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await new Blob([head,tail]).arrayBuffer()))].join(',');}if(file.size!==entry.size || !original || await fingerprint(file)!==await fingerprint(original))throw new Error(E('文件大小或内容不匹配，未修改原录像。','File size or content differs; original unchanged.'));await updateRecording(entry.id,{diskHandle:handle,diskName:file.name});await renderRecordingLibrary();});
// Only files explicitly dropped by the user are imported.
document.addEventListener('dragover',event=>{if(event.dataTransfer?.types.includes('Files'))event.preventDefault();});document.addEventListener('drop',async event=>{if(!event.dataTransfer?.files.length)return;event.preventDefault();for(const file of event.dataTransfer.files){try{await importRecording(file);}catch(error){$('library-status').textContent=error.message;}}});
if('mediaSession' in navigator){navigator.mediaSession.setActionHandler('play',()=>$('preview').play());navigator.mediaSession.setActionHandler('pause',()=>$('preview').pause());navigator.mediaSession.setActionHandler('seekbackward',details=>seekRecordingTimeline(playbackTimelineTime()-(details.seekOffset||10)));navigator.mediaSession.setActionHandler('seekforward',details=>seekRecordingTimeline(playbackTimelineTime()+(details.seekOffset||10)));}

async function mergeRecordingParts(entry,compatible=false){
 if(!entry)throw new Error(E('请选择一条连续录像。','Select one continuous recording.'));const parts=entry._parts || recordingGroups((await readStore('recordings')).filter(e=>!e.deletedAt)).find(e=>e.id===entry.id)?._parts;
 if(!parts || parts.length<2)throw new Error(E('至少需要两个分段。','At least two parts are required.'));
 const health=await connectHelper();if(!health?.merge)throw new Error(E('请启动新版增强包（支持分段合并）。','Start the updated helper with merge support.'));
 const uploads=[];for(const [index,part] of parts.entries()){$('library-status').textContent=E('正在传入分段 ','Uploading part ')+(index+1)+' / '+parts.length;const blob=await readStore('videos',part.id);if(!blob)throw new Error(L('errEmpty'));uploads.push((await(await enhancementRequest('/uploads',{method:'POST',body:blob})).json()).id);}
 const job=await(await enhancementRequest('/jobs/merge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parts:uploads,compatible,name:entry.name,sourceId:parts[0].id})})).json();
 const task={id:job.id,sourceId:parts[0].id,name:entry.name,mode:'merge',compatible,state:'queued',createdAt:Date.now(),exportFolder:entry.exportFolder};await runTx('tasks','readwrite',tx=>tx.objectStore('tasks').put(task));navigateWorkspace('tasks');await renderEnhancementTasks();
}
libraryAction('library-merge','合并所选连续录像','Merge selected recording',async()=>{if(librarySelection.size!==1)throw new Error(E('请选择一条连续录像。','Select one continuous recording.'));const group=recordingGroups((await readStore('recordings')).filter(e=>!e.deletedAt)).find(e=>e.id===[...librarySelection][0]);await mergeRecordingParts(group,false);});
libraryAction('library-merge-compatible','兼容合并（重新编码）','Compatible merge (re-encode)',async()=>{if(librarySelection.size!==1)throw new Error(E('请选择一条连续录像。','Select one continuous recording.'));const group=recordingGroups((await readStore('recordings')).filter(e=>!e.deletedAt)).find(e=>e.id===[...librarySelection][0]);await mergeRecordingParts(group,true);});

let crossThumbGeneration=0,crossThumbUrl=null,crossThumbTimer;
$('rotated-seek').addEventListener('pointerleave',()=>{crossThumbGeneration++;clearTimeout(crossThumbTimer);cinemaThumbnail.hidden=true;});
window.addEventListener('pagehide',()=>{if(crossThumbUrl)URL.revokeObjectURL(crossThumbUrl);if(playerSubtitleUrl)URL.revokeObjectURL(playerSubtitleUrl);playerAudioContext?.close();});

const enhanceStrength=proControl('enhance-strength','增强强度（自然修复 / 明暗 / AI 2×）','Strength (Natural / brightness / AI 2×)','range','1','0','1','.05');$('enhance-mode-hint').after(enhanceStrength);
const ambientCanvas=document.createElement('canvas');ambientCanvas.id='playback-ambient';ambientCanvas.width=96;ambientCanvas.height=54;ambientCanvas.hidden=true;$('playback-stage').prepend(ambientCanvas);const ambientToggle=proControl('playback-ambient-toggle','柔和背景填充','Soft ambient background','checkbox');rotationMenu.querySelector('.playback-toolbar').append(ambientToggle);$('playback-ambient-toggle').onchange=()=>{ambientCanvas.hidden=!$('playback-ambient-toggle').checked;savePlaybackState();};let ambientLast=0;function paintAmbient(now){if(!ambientCanvas.hidden && now-ambientLast>200 && $('preview').readyState>=2){ambientLast=now;ambientCanvas.getContext('2d').drawImage($('preview'),0,0,96,54);}if(!$('preview').paused)$('preview').requestVideoFrameCallback?.(paintAmbient);}$('preview').addEventListener('play',()=>{$('preview').requestVideoFrameCallback?.(paintAmbient);});
$('playback-stage').addEventListener('wheel',event=>{if(event.target.closest('input,select,button,details'))return;event.preventDefault();if(event.shiftKey)seekRecordingTimeline(playbackTimelineTime()+(event.deltaY>0?5:-5)).catch(error=>setNotice(error.message));else $('preview').volume=Math.max(0,Math.min(1,$('preview').volume+(event.deltaY>0?-.03:.03)));},{passive:false});
$('playback-stage').ondblclick=event=>{if(event.target.closest('.player-control-deck'))return;if(playbackZoom>1){playbackZoom=1;playbackPan={x:0,y:0};$('playback-zoom').value='1';layoutPlaybackRotation();}else $('playback-fullscreen').click();};

const helperLaunch=document.createElement('a');helperLaunch.id='helper-launch';helperLaunch.className='quiet';helperLaunch.href='wescreen-helper://start';helperLaunch.textContent=E('启动本机增强包','Start local helper');const helperLaunchHint=document.createElement('p');helperLaunchHint.className='hint';helperLaunchHint.textContent=E('macOS 首次运行增强包里的 install-launcher.command，之后可一键启动。未安装时点击安装说明；浏览器无法判断程序是否已安装。','On macOS, run install-launcher.command once to enable one-click launch. Use setup instructions if uninstalled; the browser cannot detect installation.');$('helper-actions').append(helperLaunch,helperLaunchHint);helperLaunch.onclick=()=>{setTimeout(()=>connectHelper(),2000);};
const helperDiagnosis=document.createElement('button');helperDiagnosis.type='button';helperDiagnosis.id='helper-diagnosis';helperDiagnosis.textContent=E('连接诊断','Connection diagnostics');helperDiagnosis.onclick=async()=>{const began=performance.now();await connectHelper();$('helper-status').textContent+=helperHealth ? ` · ${helperHealth.version || E('旧版本','older version')} · ${Math.round(performance.now()-began)} ms · `+E('磁盘可用 ','Disk free ')+fmtBytes(helperHealth.diskFree || 0):E(' · 检查本机程序启动、扩展配对和浏览器本地网络权限。',' · Check helper startup, extension pairing, and browser local-network permission.');};$('helper-actions').append(helperDiagnosis);

playerAction('player-audio-repair','修复声音并另存（视频保真）','Repair audio & save (original video quality)',async()=>{if(!await connectHelper())throw new Error(L('helperOffline'));const source=await readStore('recordings',activePlaybackId);if(!source)throw new Error(L('errEmpty'));await submitProcessing(source,{mode:'audio',audioPreset:audioSelect.value==='original'?'level':audioSelect.value,preview:false});navigateWorkspace('tasks');await renderEnhancementTasks();});

const realtimePreference=document.createElement('label');realtimePreference.textContent=E('实时 AI 策略','Realtime AI strategy');const realtimeStrategy=document.createElement('select');realtimeStrategy.id='realtime-strategy';for(const [value,zh,en] of [['preserve','原始细节优先','Preserve source detail'],['smooth','流畅优先（允许降低处理分辨率）','Smoothness (may reduce resolution)']]){const option=document.createElement('option');option.value=value;option.textContent=E(zh,en);realtimeStrategy.append(option);}realtimePreference.append(realtimeStrategy);qualityPanel.append(realtimePreference);
const textProtection=proControl('realtime-text-protect','桌面文字保护（保持原画）','Protect desktop text (keep original)','checkbox');textProtection.querySelector('input').checked=true;qualityPanel.append(textProtection);
