// Professional capture controls. Original blobs and the v4 database remain intact.
let captureDirectory=null,captureAudioNodes={},captureAudioMeter=null,captureMonitor=null,captureStatsTimer=null;
const proLabel=(zh,en)=>E(zh,en);
function proControl(id,zh,en,type='range',value='1',min='0',max='2',step='.05'){
 const label=document.createElement('label'),span=document.createElement('span'),input=document.createElement('input');span.textContent=proLabel(zh,en);input.id=id;input.type=type;input.value=value;if(type==='range'){input.min=min;input.max=max;input.step=step;}label.append(span,input);return label;
}
const capturePro=document.createElement('details');capturePro.className='advanced';capturePro.id='capture-pro';
const captureProTitle=document.createElement('summary');captureProTitle.textContent=E('专业录制与声音','Professional capture & audio');capturePro.append(captureProTitle);
const captureProGrid=document.createElement('div');captureProGrid.className='grid';
for(const item of [['system-gain','系统音量','System gain'],['mic-gain','麦克风音量','Microphone gain']])captureProGrid.append(proControl(...item));
const limiter=proControl('capture-limiter','防止爆音','Peak protection','checkbox');limiter.querySelector('input').checked=true;captureProGrid.append(limiter);
const voice=proControl('capture-voice','人声降噪（音乐录制请关闭）','Voice noise reduction (off for music)','checkbox');voice.querySelector('input').checked=true;captureProGrid.append(voice);
const independent=proControl('capture-tracks','额外保留系统音与麦克风独立音轨','Keep separate system and microphone audio files','checkbox');captureProGrid.append(independent);
const scene=document.createElement('label');scene.textContent=E('编码场景','Encoding content');const select=document.createElement('select');select.id='capture-content';for(const [value,zh,en] of [['auto','自动','Auto'],['detail','文字与桌面','Text & desktop'],['motion','运动视频','Motion video']]){const o=document.createElement('option');o.value=value;o.textContent=E(zh,en);select.append(o);}scene.append(select);captureProGrid.append(scene);capturePro.append(captureProGrid);
const audioQuality=document.createElement('label');audioQuality.textContent=E('录音品质','Audio encoding');const audioQualitySelect=document.createElement('select');audioQualitySelect.id='capture-audio-quality';for(const [value,zh,en] of [['192000','人声 · 192 kbps','Speech · 192 kbps'],['256000','音乐 · 256 kbps','Music · 256 kbps']]){const option=document.createElement('option');option.value=value;option.textContent=E(zh,en);audioQualitySelect.append(option);}captureProGrid.append(audioQuality);audioQuality.append(audioQualitySelect);
const diskControls=document.createElement('div');diskControls.className='controls';const chooseDisk=document.createElement('button');chooseDisk.id='capture-folder';chooseDisk.type='button';chooseDisk.textContent=E('选择磁盘保存目录','Choose recording folder');const clearDisk=document.createElement('button');clearDisk.type='button';clearDisk.textContent=E('仅存录像库','Library only');const diskStatus=document.createElement('p');diskStatus.id='capture-folder-status';diskStatus.className='hint';diskControls.append(chooseDisk,clearDisk);capturePro.append(diskControls,diskStatus);
$('segment-minutes').closest('details')?.append(capturePro);if(!capturePro.isConnected)$('setup').append(capturePro);
async function updateCaptureDirectory(){diskStatus.textContent=captureDirectory ? E('同步保存到所选目录：','Also saving to selected folder: ')+captureDirectory.name+E('。按安全分段写入，原视频仍在录像库。','; written in safe segments, originals also stay in the library.'):E('原视频保存在录像库。选择目录后额外持续写入磁盘，无需自动下载。','Originals are in the library. Choose a folder for additional direct disk writes.');}
chooseDisk.onclick=async()=>{try{if(!window.showDirectoryPicker)throw new Error(E('此浏览器不支持目录写入，请使用下载导出。','Folder writing is unavailable; use Export.'));captureDirectory=await showDirectoryPicker({id:'wescreen-recordings',mode:'readwrite'});await runTx('meta','readwrite',tx=>tx.objectStore('meta').put(captureDirectory,'capture-directory'));await updateCaptureDirectory();}catch(error){if(error.name!=='AbortError')diskStatus.textContent=error.message;}};
clearDisk.onclick=async()=>{captureDirectory=null;await runTx('meta','readwrite',tx=>tx.objectStore('meta').delete('capture-directory'));updateCaptureDirectory();};
readStore('meta','capture-directory').then(async handle=>{if(handle && await handle.queryPermission({mode:'readwrite'})==='granted')captureDirectory=handle;else if(handle)diskStatus.textContent=E('保存目录需要重新授权，请点击选择目录。','Reauthorize your recording folder.');if(!handle || captureDirectory)updateCaptureDirectory();}).catch(error=>diskStatus.textContent=error.message);
for(const id of ['system-gain','mic-gain'])$(id).oninput=()=>captureAudioNodes[id]?.gain.setTargetAtTime(Number($(id).value),mixer.currentTime,.02);
function configureCaptureAudio(context,destination,streams){
 captureAudioNodes={};const bus=context.createGain(),peak=context.createDynamicsCompressor();peak.threshold.value=-3;peak.knee.value=0;peak.ratio.value=20;peak.attack.value=.003;peak.release.value=.15;
 bus.connect($('capture-limiter')?.checked ? peak:destination);if($('capture-limiter')?.checked){const ceiling=context.createWaveShaper(),curve=new Float32Array(4097);for(let i=0;i<curve.length;i++)curve[i]=Math.max(-.95,Math.min(.95,i*2/(curve.length-1)-1));ceiling.curve=curve;ceiling.oversample='4x';peak.connect(ceiling).connect(destination);}
 captureAudioMeter=context.createAnalyser();captureAudioMeter.fftSize=512;bus.connect(captureAudioMeter);
 for(const [stream,id] of [[streams[0],'system-gain'],[streams[1],'mic-gain']]){if(!stream?.getAudioTracks().length)continue;const gain=context.createGain();gain.gain.value=Number($(id)?.value ?? 1);context.createMediaStreamSource(stream).connect(gain).connect(bus);captureAudioNodes[id]=gain;}
}
async function prepareDiskCapture(){if(captureDirectory && await captureDirectory.queryPermission({mode:'readwrite'})!=='granted')throw new Error(E('保存目录权限失效，请重新选择目录后再录制。','Recording folder permission expired. Choose it again.'));}
function writeDiskChunk(state,blob){if(!captureDirectory)return;const directory=captureDirectory;state.diskChain=(state.diskChain || Promise.resolve()).then(async()=>{if(!state.diskWriter){let name=state.name.replace(/[\\/:*?"<>|]/g,'-');name=name.replace(/(\.[^.]+)$/,`-${state.session}$1`);const handle=await directory.getFileHandle(name,{create:true});state.diskHandle=handle;state.diskName=name;state.diskWriter=await handle.createWritable();}await state.diskWriter.write(blob);}).catch(error=>{state.diskFailed=true;setNotice(E('磁盘同步失败，录像库与恢复片段继续保存：','Disk copy failed; library and recovery remain active: ')+error.message);});return state.diskChain;}
async function closeDiskSegment(state){await state.diskChain;if(state.diskWriter){try{if(state.diskFailed)await state.diskWriter.abort();else{await state.diskWriter.close();state.details={...state.details,diskName:state.diskName,diskHandle:state.diskHandle};}}catch(error){state.diskFailed=true;setNotice(error.message);}state.diskWriter=null;}}
let independentTracks=[];
function startIndependentAudio(){stopIndependentAudio();if(!$('capture-tracks').checked)return;for(const [stream,label] of [[displayStream,'system'],[micStream,'microphone']]){if(!stream?.getAudioTracks().length)continue;const type=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm',session=crypto.randomUUID(),state={name:`${sanitized()}-${label}.webm`,session,diskChain:Promise.resolve()};let sequence=0;const encoder=new MediaRecorder(new MediaStream(stream.getAudioTracks()),{mimeType:type,audioBitsPerSecond:captureAudioBitrate()});let writes=Promise.resolve();encoder.ondataavailable=e=>{if(!e.data.size)return;const seq=++sequence;writes=writes.then(()=>saveChunk(e.data,session,seq)).catch(error=>{setNotice(error.message);stop();});writeDiskChunk(state,e.data);};encoder.onstop=async()=>{try{await writes;await closeDiskSegment(state);await runTx('meta','readwrite',tx=>tx.objectStore('meta').put({name:state.name,session,mimeType:type,audioOnly:true},'audio:'+session));}catch(error){setNotice(error.message);}};runTx('meta','readwrite',tx=>tx.objectStore('meta').put({name:state.name,session,mimeType:type,audioOnly:true},'audio:'+session)).catch(error=>setNotice(error.message));encoder.start(1000);independentTracks.push(encoder);}}
function stopIndependentAudio(){for(const encoder of independentTracks)if(encoder.state!=='inactive')encoder.stop();independentTracks=[];}
const qualityStats=document.createElement('p');qualityStats.id='capture-quality-stats';qualityStats.className='hint';qualityStats.setAttribute('role','status');$('recording').append(qualityStats);
function startCaptureStats(){clearInterval(captureStatsTimer);const v=$('live-preview'),samples=new Float32Array(512);let previousFrames=0,previousTime=performance.now(),silence=0,lastFrame=performance.now();const frame=()=>{lastFrame=performance.now();if(recorder && recorder.state!=='inactive')v.requestVideoFrameCallback?.(frame);};v.requestVideoFrameCallback?.(frame);
 captureStatsTimer=setInterval(async()=>{if(!recorder || recorder.state==='inactive'){clearInterval(captureStatsTimer);return;}const settings=displayStream?.getVideoTracks()[0]?.getSettings()||{},q=v.getVideoPlaybackQuality?.(),now=performance.now(),fps=q?Math.max(0,Math.round((q.totalVideoFrames-previousFrames)*1000/(now-previousTime))):null;previousFrames=q?.totalVideoFrames||0;previousTime=now;let rms=0,peak=0;if(captureAudioMeter){captureAudioMeter.getFloatTimeDomainData(samples);for(const x of samples){rms+=x*x;peak=Math.max(peak,Math.abs(x));}rms=Math.sqrt(rms/samples.length);}silence=rms<.0001?silence+1:0;const muted=pausedAt || document.hidden;const alerts=[];if(!muted && now-lastFrame>5000)alerts.push(E('预览帧长时间未更新，请检查共享画面','Preview frames stalled; check shared source'));if(!pausedAt && captureAudioMeter && silence>10)alerts.push(E('连续无声，请检查源音量','No audio detected; check source volume'));if(!pausedAt && Date.now()-lastRecordingWrite>15000)alerts.push(E('录制片段写入延迟，请检查磁盘与浏览器状态','Recording writes delayed; check storage and browser'));if(peak>.98)alerts.push(E('声音接近削波，请降低音量','Audio near clipping; reduce gain'));qualityStats.textContent=`${settings.width||'?'}×${settings.height||'?'} · `+E('预览 ','Preview ')+`${fps===null?'?':fps} fps · `+E('预览掉帧 ','Preview dropped ')+(q?.droppedVideoFrames||0)+` · ${rms ? (20*Math.log10(rms)).toFixed(1):'−∞'} dBFS`+(activeSegment?.bytes?' · '+E('成片平均（含声音） ','Measured output incl. audio ')+(activeSegment.bytes*8/Math.max(1,(elapsed()-activeSegment.start)/1000)/1e6).toFixed(1)+' Mbps':'')+(alerts.length?' · '+alerts.join(' · '):'');if(now-previousDiskCheck>10000){previousDiskCheck=now;const estimate=await navigator.storage.estimate();if(estimate.quota-estimate.usage<STORAGE_FLOOR_BYTES)qualityStats.textContent+=' · '+E('浏览器可用空间不足','Browser storage low');}},1000);}
let previousDiskCheck=0;

const monitorButton=document.createElement('button');monitorButton.type='button';monitorButton.id='capture-monitor';monitorButton.textContent=E('耳机监听（录制中）','Headphone monitor (during recording)');monitorButton.onclick=()=>{if(!mixer || !captureAudioMeter)return setNotice(E('开始录制后可试听混音；请使用耳机防止回声。','Start recording to monitor the mix; use headphones to avoid feedback.'));if(captureMonitor){captureAudioMeter.disconnect(captureMonitor);captureMonitor.disconnect();captureMonitor=null;monitorButton.setAttribute('aria-pressed','false');}else{captureMonitor=mixer.createGain();captureAudioMeter.connect(captureMonitor).connect(mixer.destination);monitorButton.setAttribute('aria-pressed','true');}};capturePro.append(monitorButton);$('recording').append(monitorButton.cloneNode(true));$('recording').lastChild.id='capture-monitor-live';$('capture-monitor-live').onclick=()=>{monitorButton.onclick();$('capture-monitor-live').setAttribute('aria-pressed',monitorButton.getAttribute('aria-pressed')||'false');};
SETTING_FIELDS.push(['system-gain','text'],['mic-gain','text'],['capture-limiter','checked'],['capture-voice','checked'],['capture-tracks','checked'],['capture-content','select'],['capture-audio-quality','select']);
for(const id of ['system-gain','mic-gain','capture-limiter','capture-voice','capture-tracks','capture-content','capture-audio-quality'])$(id).addEventListener('change',persist);

window.addEventListener('wescreen-language',()=>{audioQuality.firstChild.textContent=E('录音品质','Audio encoding');audioQualitySelect.options[0].textContent=E('人声 · 192 kbps','Speech · 192 kbps');audioQualitySelect.options[1].textContent=E('音乐 · 256 kbps','Music · 256 kbps');});

audioQualitySelect.addEventListener('change',()=>{if(audioQualitySelect.value==='256000'){$('capture-voice').checked=false;persist();}});
