const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../telegram.js'),'utf8');
function monitor(){let tick,now=0,status,pauseCount=0,stops=0;const recorder={state:'recording'},diagnostic={},ctx={clearInterval(){},setInterval(fn){tick=fn;return 1;},Date:{now:()=>now},chrome:{runtime:{sendMessage:async()=>status}},recorder,activeSegment:{channelMetadata:{captureDiagnostics:diagnostic}},captureChannelContext:{messageId:'101',channelKey:'public:channel'},compositor:{telegramCrop:true,worker:{postMessage(){}}},$:id=>({value:id==='capture-mode'?'telegram':'tab'}),E:(zh,en)=>en,pause(){pauseCount++;recorder.state=recorder.state==='recording'?'paused':'recording';},stop(){stops++;recorder.state='inactive';}};vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('let telegramEndTimer'),source.indexOf('async function telegramSelectedVideoStatus')),ctx);ctx.startTelegramSourceMonitor();return {ctx,diagnostic,recorder,get pauses(){return pauseCount},get stops(){return stops},async poll(s){status=s;now+=1000;await tick();}};}
test('verified buffering pauses and resumes only an automatically paused recording',async()=>{const m=monitor(),s={verified:true,time:1,readyState:2,paused:false,ended:false,duration:20,region:{}};await m.poll(s);await m.poll(s);await m.poll(s);await m.poll(s);assert.equal(m.recorder.state,'paused');assert.equal(m.diagnostic.bufferPauses,1);await m.poll({...s,time:2,readyState:4});assert.equal(m.recorder.state,'recording');m.recorder.state='paused';m.ctx.clearTelegramAutoPause();await m.poll({...s,time:3,readyState:4});assert.equal(m.recorder.state,'paused');assert.equal(m.pauses,2);});
test('still scenes and wrong messages never trigger automatic end',async()=>{const m=monitor();for(let i=0;i<5;i++)await m.poll({verified:true,time:1,readyState:4,paused:false,ended:false,duration:20,region:{}});assert.equal(m.pauses,0);await m.poll({verified:false,ended:true,time:20,duration:20});assert.equal(m.stops,0);await m.poll({verified:true,ended:true,time:20,duration:20,region:{}});assert.equal(m.stops,1);});
test('lost cropped target pauses after two probes; verification is required to resume',async()=>{const m=monitor();await m.poll({verified:false});assert.equal(m.pauses,0);await m.poll({verified:false});assert.equal(m.recorder.state,'paused');await m.poll({verified:false});assert.equal(m.recorder.state,'paused');await m.poll({verified:true,region:{},time:1,readyState:4,paused:false,ended:false});assert.equal(m.recorder.state,'recording');});
const qa={E:(zh,en)=>en};vm.createContext(qa);vm.runInContext(fs.readFileSync(path.join(__dirname,'../telegram-inspection.js'),'utf8'),qa);
test('sampling flags suspicious intervals without comparing separate parts',()=>{const pixels=new Uint8Array(4).fill(100),samples=[{part:'a',at:0,black:0,pixels},{part:'a',at:30,black:0,pixels},{part:'b',at:60,black:1,pixels},{part:'b',at:90,black:1,pixels}];const result=qa.classifyInspectionSamples(samples);assert.deepEqual(Array.from(result,w=>w.kind),['still','black']);assert.equal(result[0].start,0);assert.equal(result[1].end,90);});
test('verified source has a duration ceiling even when ended flag never arrives',async()=>{const m=monitor();const s={verified:true,time:.5,readyState:4,paused:false,ended:false,duration:3,region:{}};await m.poll(s);await m.poll(s);await m.poll(s);assert.equal(m.stops,0);await m.poll(s);assert.equal(m.stops,1);});
