// Real MediaRecorder quality and audio checks in a disposable extension profile.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-quality-'));let context;
try{
 context=await chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`,'--autoplay-policy=no-user-gesture-required']});await context.route('http://127.0.0.1:8765/**',r=>r.abort());const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),page=await context.newPage(),id=new URL(worker.url()).host,errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
 await page.evaluate(()=>{$('capture-audio-quality').value='256000';$('capture-audio-quality').dispatchEvent(new Event('change'));});assert.equal(await page.evaluate(()=>captureAudioBitrate()),256000);assert.equal(await page.locator('#capture-voice').isChecked(),false);
 await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=180;canvas.height=320;const ctx=canvas.getContext('2d');window.qualityDraw=setInterval(()=>{ctx.fillStyle=`hsl(${performance.now()%360},100%,50%)`;ctx.fillRect(0,0,180,320);},20);window.qualityAudio=new AudioContext({sampleRate:48000});const oscillator=qualityAudio.createOscillator(),gain=qualityAudio.createGain(),dest=qualityAudio.createMediaStreamDestination();gain.gain.value=.2;oscillator.connect(gain).connect(dest);oscillator.start();await qualityAudio.resume();navigator.mediaDevices.getDisplayMedia=async()=>new MediaStream([...canvas.captureStream(25).getVideoTracks(),...dest.stream.getAudioTracks()]);$('preflight-enabled').checked=false;$('countdown').value='0';$('microphone').checked=false;$('clicks').checked=false;$('quiet-tab-audio').checked=false;$('capture-method').value='shared';$('framerate').value='25';$('resolution').value='1080';$('format').value='mp4';await start();});await page.waitForFunction(()=>recorder?.state==='recording');
 assert.match(await page.locator('#capture-resolution-help').textContent(),/Target bitrate|目标码率/);assert.match(await page.locator('#capture-resolution-help').textContent(),/Encoder reported|编码器报告/);assert.equal(await page.evaluate(()=>recorder.audioBitsPerSecond),256000);await page.waitForTimeout(1800);await page.evaluate(()=>stop());await page.waitForFunction(()=>recorder===null&&finalId);
 const entry=await page.evaluate(()=>readStore('recordings',finalId));assert.equal(entry.width,180);assert.equal(entry.height,320);assert.ok(entry.averageMuxBitrate>0);assert.equal(entry.encoderAudioBitrate,256000);assert.equal(entry.captureContent,'detail');assert.ok(entry.frameRate>0);
 const bytes=await page.evaluate(async()=>[...new Uint8Array(await(await readStore('videos',finalId)).arrayBuffer())]);const output=path.join(temp,'recorded.mp4');fs.writeFileSync(output,Buffer.from(bytes));const streams=JSON.parse(cp.execFileSync('ffprobe',['-v','error','-show_streams','-of','json',output],{encoding:'utf8'})).streams;assert.ok(streams.some(s=>s.codec_name==='h264'&&s.width===180&&s.height===320));assert.ok(streams.some(s=>s.codec_name==='aac'&&s.sample_rate==='48000'&&s.channels===2));
 // A real hot stereo signal through the optional peak-protection path stays bounded.
 const peak=await page.evaluate(async()=>{const audio=new AudioContext(),oscillator=audio.createOscillator(),gain=audio.createGain(),input=audio.createMediaStreamDestination(),output=audio.createMediaStreamDestination(),meter=audio.createAnalyser();gain.gain.value=4;oscillator.connect(gain).connect(input);$('capture-limiter').checked=true;configureCaptureAudio(audio,output,[input.stream,null]);audio.createMediaStreamSource(output.stream).connect(meter);meter.fftSize=2048;oscillator.start();await audio.resume();await new Promise(r=>setTimeout(r,300));const data=new Float32Array(2048);meter.getFloatTimeDomainData(data);const peak=Math.max(...data.map(Math.abs));oscillator.stop();await audio.close();return peak;});assert.ok(peak>.1&&peak<1,`Peak protection failed: ${peak}`);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({music256k:true,micDspDisabledForMusic:true,targetAndEncoderDistinguished:true,portraitPreserved:true,qualityMetadataSaved:true,h264Aac48kStereo:true,peakProtection:peak,errors}));
}finally{await context?.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
