// Upgrade in-place in an isolated Chromium profile; verify binary recordings, recovery data and preferences.
const {chromium}=require('playwright'),fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),assert=require('assert/strict');
(async()=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-upgrade-')),ext=path.join(temp,'extension'),profile=path.join(temp,'profile');fs.mkdirSync(ext);let context;
 const unpack=version=>{const p=cp.spawnSync('python3',['-c','import zipfile,sys;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',path.join(root,'store',`wescreen-${version}.zip`),ext]);assert.equal(p.status,0);};
 const launch=async()=>{const cx=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`]});await cx.route('http://127.0.0.1:8765/**',r=>r.abort());return cx;};
 const snapshot=page=>page.evaluate(async()=>{const database=await db;const output={};for(const name of ['recordings','videos','chunks','meta','tasks']){const entries=await new Promise((resolve,reject)=>{const tx=database.transaction(name),store=tx.objectStore(name),rows=[],r=store.openCursor();r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(c){rows.push([c.key,c.value]);c.continue();}else resolve(rows);};});output[name]=await Promise.all(entries.map(async([key,value])=>[key,value instanceof Blob ? {type:value.type,size:value.size,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',await value.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('')}:value]));}output.preferences=await chrome.storage.local.get(['lang','upgrade-test-preferences']);output.version=database.version;return output;});
 try{
  unpack('1.13.0');context=await launch();let worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).host,page=await context.newPage();await page.goto(`chrome-extension://${id}/popup.html`);
  await page.evaluate(async()=>{await chrome.storage.local.set({lang:'zh','upgrade-test-preferences':{channel:'preserved',quality:'high'}});await new Promise((resolve,reject)=>{const r=indexedDB.open('wescreen',3);r.onupgradeneeded=()=>{for(const store of ['videos','chunks','meta'])r.result.createObjectStore(store);r.result.createObjectStore('recordings',{keyPath:'id'});};r.onerror=()=>reject(r.error);r.onsuccess=()=>{const d=r.result,tx=d.transaction(['videos','chunks','meta','recordings'],'readwrite');const b=new Blob([new Uint8Array([0,1,127,128,254,255])],{type:'video/mp4'});tx.objectStore('videos').put(b,'old-recording');tx.objectStore('recordings').put({id:'old-recording',name:'old-video.mp4',size:6,createdAt:1,course:'Old channel'});tx.objectStore('chunks').put(b,'unfinished-000000');tx.objectStore('meta').put({session:'unfinished',name:'recover.mp4'},'session:unfinished');tx.objectStore('meta').put({time:12,rotation:90},'playback:old-recording');tx.oncomplete=()=>{d.close();resolve();};tx.onerror=()=>reject(tx.error);};});});
  await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');await page.evaluate(async()=>{await runTx('tasks','readwrite',tx=>tx.objectStore('tasks').put({id:'old-task',sourceId:'old-recording',state:'done'}));});const before=await snapshot(page);assert.equal(before.version,4);assert.equal(before.videos[0][1].size,6);assert.equal(before.chunks.length,1);await context.close();context=null;
  const latest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'))).version;unpack(latest);context=await launch();worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');assert.equal(new URL(worker.url()).host,id,'Updating the same directory must preserve extension ID');page=await context.newPage();await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');const after=await snapshot(page);assert.deepEqual(after,before);assert.equal(await page.evaluate(()=>chrome.runtime.getManifest().version),latest);
  console.log(JSON.stringify({from:'1.13.0',to:latest,sameExtensionId:true,legacyDatabaseMigration:'3 → 4',videoBytesAndHashPreserved:true,recordingsPreserved:true,recoveryChunksPreserved:true,playbackStatePreserved:true,tasksPreserved:true,preferencesPreserved:true}));
 }finally{if(context)await context.close();fs.rmSync(temp,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
