const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawnSync}=require('child_process');
(async()=>{const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-studio-')),screens=path.resolve(root,'../audit-2026-10-04/studio');fs.mkdirSync(screens,{recursive:true});let context;
try{
 context=await chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,viewport:{width:1440,height:1000},args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`,'--autoplay-policy=no-user-gesture-required']});
 await context.route('http://127.0.0.1:8765/**',route=>route.abort());
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).host,page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');await page.evaluate(()=>applyLang('zh'));
 assert.equal(await page.locator('.workspace-nav [data-view]').count(),6);await page.evaluate(()=>navigateWorkspace('player'));assert.equal(await page.locator('#player-empty').isVisible(),true);await page.evaluate(()=>navigateWorkspace('capture'));
 assert.equal(await page.locator('.scenario-picker').isVisible(),false);assert.equal(await page.locator('.studio-source').count(),1);assert.equal(await page.locator('.studio-record-settings #framerate').count(),1);
 assert.equal(await page.evaluate(async()=>(await document.fonts.load('500 16px "WeScreen Source Han Sans"','录制视频')).length),1);
 const source=await page.locator('.studio-source').boundingBox(),settings=await page.locator('.studio-record-settings').boundingBox();assert.ok(Math.abs(source.height-settings.height)<2,'Recording columns must align');
 await page.screenshot({path:path.join(screens,'01-record.png'),fullPage:true});
 await page.evaluate(async()=>{telegramProfiles=[{id:'menu-design',name:'示例频道',channelProfile:true,plan:[{id:'demo-1',title:'视频 986',url:'https://t.me/c/1234567890/986',status:'waiting'},{id:'demo-2',title:'视频 987',url:'https://t.me/c/1234567890/987',status:'waiting'}]}];const option=document.createElement('option');option.value='menu-design';option.textContent='示例频道';$('channel-select').append(option);$('channel-select').value='menu-design';navigateWorkspace('channels');await renderChannelWorkbench();});
 await page.locator('.plan-row-menu > summary').first().click();assert.equal(await page.locator('.plan-row-menu .menu-items').first().locator('button').count(),5);assert.equal(await page.locator('.plan-row-menu .menu-items').first().locator('button').nth(2).isDisabled(),true);
 await page.screenshot({path:path.join(screens,'11-telegram-menu.png'),fullPage:true});
 await page.evaluate(async()=>{await runTx('recordings','readwrite',tx=>tx.objectStore('recordings').put({id:'menu-preserved',name:'Existing.mp4',channelTaskId:'demo-1'}));});
 page.once('dialog',dialog=>dialog.accept());await page.locator('.plan-remove').first().click();await page.waitForFunction(async()=>{const profile=await readStore('meta','channel:menu-design');return profile?.plan.length===1;});assert.equal(await page.evaluate(async()=>!!await readStore('recordings','menu-preserved')),true);await page.evaluate(async()=>{await runTx('recordings','readwrite',tx=>tx.objectStore('recordings').delete('menu-preserved'));navigateWorkspace('capture');});

 await page.evaluate(async()=>{await chrome.storage.local.set({settings:{'capture-mode':'telegram',filename:'Private-channel-002',resolution:'1080',quality:'high',framerate:'60'}});});await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');assert.equal(await page.evaluate(()=>$('capture-mode').value),'general');assert.equal(await page.locator('#telegram-guide').isVisible(),false);assert.equal(await page.locator('#telegram-channel').isVisible(),false);assert.equal(await page.evaluate(()=>$('filename').value),'wescreen-recording');assert.equal(await page.evaluate(()=>$('framerate').value),'60');
 const clip=path.join(temp,'clip.mp4');assert.equal(spawnSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=640x360:rate=30','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','3','-c:v','libx264','-c:a','aac',clip]).status,0);
 await page.evaluate(async b64=>{const blob=new Blob([Uint8Array.from(atob(b64),c=>c.charCodeAt(0))],{type:'video/mp4'});$('live-preview').src=URL.createObjectURL(blob);$('timer').textContent='00:23';$('source-info').textContent='共享视频源 · 1920×1080 · 30 fps';$('memory').textContent='已录制 84 MB';$('live-level').value=.35;show('recording');},fs.readFileSync(clip).toString('base64'));
 await page.waitForFunction(()=>$('live-preview').readyState>=2);await page.locator('#live-preview').evaluate(v=>v.pause());
 assert.equal(await page.locator('.recording-transport #stop').count(),1);const previewBox=await page.locator('#live-preview').boundingBox(),dockBox=await page.locator('.recording-control-dock').boundingBox();assert.ok(dockBox.y>=previewBox.y+previewBox.height,'Recording dock must not overlap video');assert.ok(Math.abs(previewBox.width/previewBox.height-640/360)<.02,'Preview box follows source aspect ratio');assert.equal(await page.locator('.recording-diagnostics').getAttribute('open'),null);
 await page.screenshot({path:path.join(screens,'10-recording-console.png'),fullPage:true});await page.evaluate(()=>show('setup'));
 await page.evaluate(async b64=>{const blob=new Blob([Uint8Array.from(atob(b64),c=>c.charCodeAt(0))],{type:'video/mp4'});await runTx(['recordings','videos'],'readwrite',tx=>{for(const e of [{id:'studio-original',name:'Studio-demo.mp4'},{id:'studio-restored',name:'Studio-demo-natural.mp4',enhancedFrom:'studio-original',enhancement:'natural'}]){tx.objectStore('recordings').put({...e,size:blob.size,duration:3000,width:640,height:360,createdAt:Date.now()});tx.objectStore('videos').put(blob,e.id);}});await renderRecordingLibrary();navigateWorkspace('library');},fs.readFileSync(clip).toString('base64'));
 await page.waitForFunction(()=>document.querySelector('.studio-versions .derived-row'));assert.equal(await page.locator('#recording-library').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(20, 22, 25)');assert.equal(await page.locator('#recording-items > .media-row').count(),1);assert.equal(await page.locator('.studio-versions').getAttribute('open'),null);
 await page.locator('.studio-versions>summary').click();assert.equal(await page.locator('.derived-row').isVisible(),true);await page.locator('.studio-versions>summary').click();
 await page.locator('#recording-items > .media-row > .row-select').check();await page.locator('[data-library-layout=cards]').click();assert.equal(await page.locator('#recording-items > .media-row > .row-select').isChecked(),true);await page.locator('[data-library-layout=rows]').click();await page.screenshot({path:path.join(screens,'03-library.png'),fullPage:true});
 await page.evaluate(async()=>{await playRecording(await readStore('recordings','studio-original'));});await page.waitForFunction(()=>playbackReady&&$('preview').readyState>=2);assert.equal(await page.evaluate(()=>workspaceView),'player');assert.equal(await page.locator('#result').isVisible(),false);await page.evaluate(async()=>{await $('preview').play();});await page.waitForFunction(()=>$('preview').currentTime>.1);await page.evaluate(()=>$('preview').pause());assert.ok(await page.locator('#preview').evaluate(v=>v.getBoundingClientRect().width)>300);await page.screenshot({path:path.join(screens,'06-player.png'),fullPage:true});
 await page.locator('#playback-quality-menu>summary').click();assert.equal(await page.locator('#playback-quality-menu .cinema-popover>button:visible').count(),2);await page.screenshot({path:path.join(screens,'07-quality.png'),fullPage:true});await page.locator('#playback-quality-menu>summary').click();
 await page.locator('#playback-rotation-menu>summary').click();await page.locator('#playback-right').click();assert.equal(await page.locator('#playback-angle').inputValue(),'90');await page.screenshot({path:path.join(screens,'13-view-inspector.png'),fullPage:true});await page.locator('#playback-reset').click();assert.equal(await page.locator('#playback-angle').inputValue(),'0');await page.locator('#playback-rotation-menu>summary').click();
 await page.locator('#playback-fullscreen').click();await page.waitForFunction(()=>document.fullscreenElement?.id==='playback-shell');assert.equal(await page.evaluate(()=>Math.round($('playback-shell').getBoundingClientRect().height)),1000);await page.screenshot({path:path.join(screens,'08-fullscreen.png')});await page.evaluate(()=>document.exitFullscreen());
 await page.evaluate(async()=>{await openEnhancement(await readStore('recordings','studio-original'));});assert.equal(await page.evaluate(()=>workspaceView),'player');assert.equal(await page.evaluate(()=>$('enhance-panel').open),false);assert.equal(await page.evaluate(()=>selectedQuality),'smart');for(const id of ['playback-ai','playback-enhance','player-face-restore','player-audio-repair','batch-add'])assert.equal(await page.locator('#'+id).isVisible(),false);await page.screenshot({path:path.join(screens,'09-smart-viewing.png'),fullPage:true});
 // Direct local playback is File-backed and never modifies the library.
 const before=await page.evaluate(async()=>(await readStore('recordings')).map(e=>e.id).sort());
 await page.locator('#local-video-file').setInputFiles(clip);
 await page.waitForFunction(()=>playbackReady&&finalId===null&&finalBlob instanceof File&&$('preview').readyState>=2);
 assert.deepEqual(await page.evaluate(async()=>(await readStore('recordings')).map(e=>e.id).sort()),before);
 assert.equal(await page.locator('#playback-name').textContent(),'clip.mp4');
 await page.evaluate(()=>$('preview').pause());await page.locator('#rotated-seek').click();await page.waitForFunction(()=>!$('preview').paused&&$('preview').currentTime>0);
 // Progress uses actual chunk reports; ETA is withheld until enough work is measured.
 const progressLabels=await page.evaluate(()=>{smartBackground.enabled=true;smartBackground.session='test';smartBackground.pending=2;smartBackground.pendingStarted=performance.now()-10000;smartBackground.status={progress:.5};const halfway=smartProgressText();smartBackground.status={progress:0};const first=smartProgressText();smartBackground.status={progress:.99};const finishing=smartProgressText();smartBackground.enabled=false;smartBackground.session=null;smartBackground.pending=null;return {halfway,first,finishing};});
 assert.match(progressLabels.halfway,/50%/);assert.match(progressLabels.halfway,/00:08/);assert.match(progressLabels.halfway,/remaining|还需/);assert.doesNotMatch(progressLabels.first,/remaining|还需/);assert.match(progressLabels.finishing,/Finalizing|封装/);
 // Completed smart chunks follow the original clock; idle exit removes all media.
 await page.evaluate(async b64=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const originalRequest=enhancementRequest;window.restoreSmartRequest=()=>{enhancementRequest=originalRequest;};enhancementRequest=async(path,options={})=>{if(!path.startsWith('/smart/'))return originalRequest(path,options);if(path==='/smart/sources?content=auto')return new Response(JSON.stringify({id:'a'.repeat(32),chunkSeconds:4}));if(path.includes('result=1'))return new Response(bytes,{headers:{'Content-Type':'video/mp4'}});return new Response(JSON.stringify({state:'done',start:0,engine:'Test repair',analysis:{soft:true},duration:3}));};$('preview').pause();await startSmartBackground({smartChunks:true},null);},fs.readFileSync(clip).toString('base64'));
 await page.waitForFunction(()=>smartBackground.chunks.size===1);await page.evaluate(()=>$('preview').currentTime=.5);await page.waitForFunction(()=>!smartVideo.hidden);assert.equal(await page.evaluate(()=>smartVideo.muted),true);assert.ok(await page.evaluate(()=>Number(getComputedStyle(smartVideo).zIndex)>Number(getComputedStyle($('preview')).zIndex)));assert.ok(await page.evaluate(()=>Math.abs(smartVideo.currentTime-$('preview').currentTime)<.08));await page.evaluate(()=>$('preview').play());await page.waitForFunction(()=>$('preview').currentTime>.8&&!smartVideo.hidden);assert.ok(await page.evaluate(()=>Math.abs(smartVideo.currentTime-$('preview').currentTime)<.08));await page.evaluate(()=>$('preview').pause());
 await page.evaluate(()=>checkPlayerIdle(playerIdle.last+playerIdle.limit+1));await page.waitForFunction(()=>!$('preview').hasAttribute('src'));
 assert.equal(await page.locator('#player-empty').isVisible(),true);assert.equal(await page.evaluate(()=>smartBackground.chunks.size===0&&!smartBackground.enabled),true);assert.deepEqual(await page.evaluate(async()=>(await readStore('recordings')).map(e=>e.id).sort()),before);await page.evaluate(()=>restoreSmartRequest());
 await page.locator('#local-video-file').setInputFiles(clip);await page.waitForFunction(()=>$('preview').readyState>=2&&finalBlob instanceof File);
 await page.locator('#playback-close').click();await page.waitForFunction(()=>!$('preview').hasAttribute('src'));assert.equal(await page.locator('#player-empty').isVisible(),true);await page.locator('#local-video-file').setInputFiles(clip);await page.waitForFunction(()=>$('preview').readyState>=2&&finalBlob instanceof File);
 await page.locator('#local-video-file').setInputFiles({name:'broken.mp4',mimeType:'video/mp4',buffer:Buffer.from('invalid video')});
 await page.waitForFunction(()=>/无法解码|cannot decode/.test($('playback-status').textContent));assert.equal(await page.evaluate(()=>finalName),'clip.mp4');
 for(const [view,name]of [['channels','02-telegram'],['tasks','04-processing'],['about','05-about']]){await page.evaluate(view=>navigateWorkspace(view),view);assert.equal(await page.locator({channels:'#channel-workbench',tasks:'#tasks-view',about:'#about-view'}[view]).evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(20, 22, 25)');await page.screenshot({path:path.join(screens,name+'.png'),fullPage:true});}
 for(const lang of ['zh','en']){await page.evaluate(lang=>applyLang(lang),lang);await page.setViewportSize({width:390,height:844});for(const view of ['capture','channels','library','player','tasks','about']){await page.evaluate(view=>{navigateWorkspace(view);if(view==='capture')show('setup');},view);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,lang+' '+view+' overflow');}}
 await page.setViewportSize({width:1440,height:1000});for(const [view,selector]of [['library','#recording-library'],['channels','#channel-workbench'],['tasks','#tasks-view'],['about','#about-view']]){await page.evaluate(view=>navigateWorkspace(view),view);const inset=await page.locator(selector).evaluate(el=>{const shell=el.getBoundingClientRect(),heading=el.querySelector('h2').getBoundingClientRect();return heading.left-shell.left;});assert.ok(inset>=24,view+' text must be inset from workspace border');}
 const cache=await page.evaluate(()=>{clearRealtimeFrameCache();cacheRealtimeFrame('first',new Uint8Array(13*1024*1024),2,2);cacheRealtimeFrame('second',new Uint8Array(13*1024*1024),2,2);const bounded=realtimeCacheBytes<=24*1024*1024&&!realtimeFrameCache.has('first')&&realtimeFrameCache.has('second');stopRealtimeAI();return {bounded,cleared:realtimeCacheBytes===0&&realtimeFrameCache.size===0};});assert.deepEqual(cache,{bounded:true,cleared:true});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({version:await page.evaluate(()=>chrome.runtime.getManifest().version),sixTabs:true,rowVersions:true,selectionPreserved:true,sourceHan:true,nativeFullscreen:true,localPlaybackWithoutImport:true,invalidFileRetainsSource:true,mobileLanguages:['zh','en'],screens,errors}));
}finally{await context?.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1)});
