const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),os=require('os'),{spawn,spawnSync}=require('child_process'),assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-polish-'));let child,context;
try{
 child=spawn(path.join(root,'enhancement/.venv/bin/python'),[path.join(root,'enhancement/server.py')],{env:{...process.env,WESCREEN_PORT:'0',WESCREEN_WORK_DIR:path.join(temp,'jobs'),WESCREEN_ENHANCE_TOKEN:'isolated-polish-test-access-token'},stdio:['ignore','pipe','pipe']});
 const port=await new Promise((resolve,reject)=>{let data='';child.stdout.on('data',chunk=>{data+=chunk;const m=data.match(/Local enhancer: http:\/\/127\.0\.0\.1:(\d+)/);if(m)resolve(Number(m[1]));});child.on('error',reject);child.on('exit',()=>reject(new Error('Helper stopped')));});
 context=await chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`,'--autoplay-policy=no-user-gesture-required']});await context.route('http://127.0.0.1:8765/**',async route=>{const response=await route.fetch({url:route.request().url().replace(':8765',':'+port)});await route.fulfill({response});});
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).host,page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true'&&helperHealth?.smartTail);
 // Resolution caps and encoding bitrate are distinct, with explicit pixel labels.
 await page.selectOption('#resolution','2160');assert.match(await page.locator('#resolution option:checked').textContent(),/4K.*3840×2160/);assert.match(await page.locator('#quality option:checked').textContent(),/4K.*bitrate|4K.*码率/);await page.selectOption('#resolution','source');assert.match(await page.locator('#capture-resolution-help').textContent(),/never upscale|不会放大/);
 const clip=path.join(temp,'clip.mp4');assert.equal(spawnSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=320x180:rate=30','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','8','-c:v','libx264','-c:a','aac',clip]).status,0);
 await page.evaluate(async b64=>{const blob=new Blob([Uint8Array.from(atob(b64),c=>c.charCodeAt(0))],{type:'video/mp4'});await runTx(['recordings','videos'],'readwrite',tx=>{for(let part=1;part<=2;part++){const e={id:'polish-'+part,name:'polish-part-00'+part+'.mp4',recordingGroupId:'polish-group',part,size:blob.size,duration:8000,width:320,height:180,createdAt:Date.now()+part};tx.objectStore('recordings').put(e);tx.objectStore('videos').put(blob,e.id);}});await playRecording(await readStore('recordings','polish-1'));},fs.readFileSync(clip).toString('base64'));await page.waitForFunction(()=>playbackReady&&$('preview').readyState>=2);
 // The quality menu contains only three actionable choices and a golden current label.
 assert.equal(await page.locator('#playback-quality-menu .cinema-popover > button').count(),3);assert.match(await page.locator('#playback-quality-menu > summary').textContent(),/Original|原画/);assert.equal(await page.locator('#playback-quality-menu > summary').evaluate(el=>getComputedStyle(el).color),'rgb(232, 193, 116)');
 // A pointer drag across multiple parts changes no playback source until release.
 await page.evaluate(()=>{window.seekCalls=0;const original=seekRecordingTimeline;seekRecordingTimeline=async(...args)=>{window.seekCalls++;return original(...args);};});await page.locator('#rotated-seek').scrollIntoViewIfNeeded();const range=await page.locator('#rotated-seek').boundingBox();await page.mouse.move(range.x+range.width*.1,range.y+range.height/2);await page.mouse.down();for(let step=1;step<=20;step++)await page.mouse.move(range.x+range.width*(.1+step*.032),range.y+range.height/2);assert.equal(await page.evaluate(()=>window.seekCalls),0);await page.mouse.move(range.x+range.width*.76,range.y+range.height/2+80);await page.mouse.up();await page.waitForFunction(()=>playbackReady&&playbackPartIndex===1).catch(async()=>{const state=await page.evaluate(()=>({ready:playbackReady,index:playbackPartIndex,seekValue:$('rotated-seek').value,calls:seekCalls,gesture:seekGesture,notice:$('playback-status').textContent}));await page.screenshot({path:'/tmp/wescreen-drag-fail.png'});throw new Error('Drag: '+JSON.stringify(state)+' hit='+await page.evaluate(r=>document.elementFromPoint(r.x+r.width*.1,r.y+r.height/2)?.outerHTML,range));});assert.equal(await page.evaluate(()=>window.seekCalls),1);assert.equal(await page.evaluate(()=>playbackSeeking),false);
 // A click seeks once and starts playing, including when the source was paused.
 await page.evaluate(()=>$('preview').pause());await page.locator('#rotated-seek').click({position:{x:range.width*.25,y:range.height/2}});await page.waitForFunction(()=>playbackReady&&!$('preview').paused&&playbackPartIndex===0&&$('preview').currentTime>3.5);assert.equal(await page.evaluate(()=>window.seekCalls),2);
 // Both signs of audio offset use a separate clock; transitions retain audibility.
 for(const offset of [-.5,.5]){await page.evaluate(async offset=>{await seekRecordingTimeline(3,true);$('player-audio-delay').value=String(offset);await $('player-audio-delay').onchange();},offset);await page.waitForFunction(()=>!syncAudio.paused&&!syncBusy);await page.waitForTimeout(250);const clocks=await page.evaluate(()=>({video:playbackTimelineTime(),audio:syncAudio.currentTime,primary:playerAudioGraph.primaryGain.gain.value,aux:playerAudioGraph.auxGain.gain.value}));assert.ok(Math.abs((clocks.video-offset)-clocks.audio)<.2,JSON.stringify({offset,...clocks}));assert.ok(clocks.primary<.1&&clocks.aux>.9);}
 // Buffering gates the separate audio clock until actual video playback resumes.
 await page.evaluate(()=>$('preview').dispatchEvent(new Event('waiting')));await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>syncAudio.paused),true);await page.evaluate(()=>$('preview').dispatchEvent(new Event('playing')));await page.waitForFunction(()=>!syncAudio.paused);
 await page.evaluate(async()=>{$('player-audio-delay').value='0';await $('player-audio-delay').onchange();$('preview').pause();});
 // Hold-to-compare preserves the viewing settings and playback clock.
 await page.evaluate(()=>{$('playback-more-menu').open=true;advancedQuality.open=true;$('playback-instant').click();});await page.locator('#player-compare').scrollIntoViewIfNeeded();const compare=await page.locator('#player-compare').boundingBox(),filter=await page.locator('#preview').evaluate(v=>v.style.filter);await page.mouse.move(compare.x+compare.width/2,compare.y+compare.height/2);await page.mouse.down();assert.equal(await page.evaluate(()=>originalCompare),true);assert.equal(await page.locator('#preview').evaluate(v=>getComputedStyle(v).filter),'none');await page.mouse.up();assert.equal(await page.evaluate(()=>originalCompare),false);assert.equal(await page.locator('#preview').evaluate(v=>v.style.filter),filter);await page.evaluate(()=>{$('playback-more-menu').open=false;});
 // Local subtitles expose size and position controls without rewriting the source.
 await page.locator('#player-subtitle').setInputFiles({name:'style.srt',mimeType:'text/plain',buffer:Buffer.from('1\n00:00:00,000 --> 00:00:07,000\nSynthetic subtitle\n')});await page.waitForFunction(()=>playerSubtitleTrack?.track.cues?.length===1);await page.evaluate(()=>{$('player-subtitle-font').value='32';$('player-subtitle-font').oninput();$('player-subtitle-position').value='70';$('player-subtitle-position').oninput();});assert.equal(await page.evaluate(()=>playerSubtitleTrack.track.cues[0].line),70);assert.match(await page.locator('#player-subtitle-font').evaluate(el=>el.previousElementSibling.textContent),/Subtitle|字幕/);assert.equal(await page.locator('#playback-shell').evaluate(el=>el.style.getPropertyValue('--subtitle-size')),'32px');
 // Mandatory preview and changed-region invalidation use real delogo output.
 await page.evaluate(async()=>openWatermark(await readStore('recordings','polish-1')));await page.waitForFunction(()=>$('watermark-original').videoWidth===320);assert.equal(await page.locator('#watermark-save').isDisabled(),true);await page.locator('#watermark-preview').click();await page.waitForFunction(()=>!watermarkBusy&&!!watermarkPreviewKey,{},{timeout:20000});assert.equal(await page.locator('#watermark-save').isDisabled(),false);await page.locator('#watermark-w').fill('55');assert.equal(await page.locator('#watermark-save').isDisabled(),true);await page.locator('#watermark-preview').click();await page.waitForFunction(()=>!watermarkBusy&&!!watermarkPreviewKey,{},{timeout:20000});await page.locator('#watermark-save').click();await page.waitForFunction(()=>!watermarkBusy&&/saved|存入/.test($('watermark-status').textContent),{},{timeout:20000});assert.ok(await page.evaluate(async()=>(await readStore('recordings')).some(e=>e.enhancement==='watermark')));await page.locator('#watermark-close').click();
 // An actual 75-second frozen silent tail is queued and saved without changing the source.
 const tail=path.join(temp,'tail.mp4');assert.equal(spawnSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=160x90:rate=5:duration=3','-f','lavfi','-i','anullsrc=r=48000:cl=mono','-vf','tpad=stop_mode=clone:stop_duration=75','-t','78','-c:v','libx264','-c:a','aac',tail]).status,0);
 await page.evaluate(async b64=>{const blob=new Blob([Uint8Array.from(atob(b64),c=>c.charCodeAt(0))],{type:'video/mp4'}),entry={id:'static-tail',name:'static-tail.mp4',size:blob.size,duration:78000,width:160,height:90,createdAt:Date.now()};await runTx(['recordings','videos'],'readwrite',tx=>{tx.objectStore('recordings').put(entry);tx.objectStore('videos').put(blob,entry.id);});await queueSmartTail(entry.id,true);},fs.readFileSync(tail).toString('base64'));
 const deadline=Date.now()+20000;let trimmed;while(Date.now()<deadline){await page.evaluate(()=>processSmartTailQueue());trimmed=await page.evaluate(async()=>(await readStore('recordings')).find(e=>e.enhancement==='trimstatic'));if(trimmed)break;await new Promise(r=>setTimeout(r,200));}assert.ok(trimmed&&trimmed.duration<5000,JSON.stringify(trimmed||await page.evaluate(async()=>({queue:await readStore('meta','smart-tail-pending'),status:$('smart-tail-status').textContent,jobs:(await(await enhancementRequest('/jobs')).json()).jobs}))));assert.equal(await page.evaluate(async()=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await readStore('videos','static-tail')).arrayBuffer()))).map(v=>v.toString(16).padStart(2,'0')).join('')),require('crypto').createHash('sha256').update(fs.readFileSync(tail)).digest('hex'));
 // Actual full-screen and narrow menus: all text tools remain inside the viewport.
 await page.locator('#playback-fullscreen').click();await page.waitForFunction(()=>!!document.fullscreenElement);await page.evaluate(()=>{$('playback-more-menu').open=true;proPlayerMenu.open=true;});await page.waitForTimeout(100);let tools=await page.locator('#player-frame-back').boundingBox();assert.ok(tools.width>70&&tools.height>=36,JSON.stringify(tools));
 await page.setViewportSize({width:560,height:900});await page.evaluate(()=>placePlayerMenus());const panel=await page.locator('#playback-more-menu .cinema-popover').boundingBox();assert.ok(panel.x>=0&&panel.x+panel.width<=560,JSON.stringify(panel));
 const audit=path.join(root,'audit-2026-10-04');fs.mkdirSync(audit,{recursive:true});await page.screenshot({path:path.join(audit,'professional-tools-1.17.png')});await page.setViewportSize({width:1280,height:800});await page.evaluate(()=>{$('playback-more-menu').open=false;qualityMenu.open=true;placePlayerMenus();});await page.waitForTimeout(100);await page.screenshot({path:path.join(audit,'quality-three-options-1.17.png')});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({resolutionLabels:true,threeQualityChoices:true,goldCurrentQuality:true,dragCommitsOnce:true,clickStartsPlayback:true,signedAudioSync:true,bufferingAudioProtected:true,holdComparePreservesSettings:true,subtitleAppearance:true,watermarkPreviewAndSave:true,previewInvalidation:true,staticTailSaved:true,originalsRetained:true,menusFitNarrowViewport:true,errors}));
}finally{await context?.close();if(child&&child.exitCode===null){const done=new Promise(r=>child.once('exit',r));child.kill('SIGINT');await done;}fs.rmSync(temp,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
