const {chromium}=require('playwright'),fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-pro-'));let context;
try{const ext=path.join(temp,'extension');fs.mkdirSync(ext);const version=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'))).version;cp.execFileSync('python3',['-c','import zipfile,sys;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',path.join(root,'store',`wescreen-${version}.zip`),ext]);cp.execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=320x180:rate=30','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','4','-c:v','libx264','-c:a','aac',path.join(temp,'clip.mp4')]);
context=await chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`,'--autoplay-policy=no-user-gesture-required']});await context.route('http://127.0.0.1:8765/**',r=>r.abort());const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=new URL(worker.url()).host,page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
await page.evaluate(async b64=>{const blob=new Blob([Uint8Array.from(atob(b64),c=>c.charCodeAt(0))],{type:'video/mp4'}),entry={id:'pro-test',name:'pro.mp4',size:blob.size,duration:4000,width:320,height:180,createdAt:Date.now()};await runTx(['recordings','videos'],'readwrite',tx=>{tx.objectStore('recordings').add(entry);tx.objectStore('videos').add(blob,entry.id);});await playRecording(entry);},fs.readFileSync(path.join(temp,'clip.mp4')).toString('base64'));await page.waitForFunction(()=>playbackReady&&$('preview').readyState>=2);
await page.evaluate(()=>{$('preview').pause();$('preview').currentTime=1;});await page.waitForFunction(()=>Math.abs($('preview').currentTime-1)<.01);await page.evaluate(()=>$('player-frame-next').click());await page.waitForFunction(()=>$('preview').currentTime>1.02&&$('preview').currentTime<1.04);await page.evaluate(()=>$('player-frame-back').click());await page.waitForFunction(()=>Math.abs($('preview').currentTime-1)<.02);
await page.evaluate(async()=>{await seekRecordingTimeline(.5,false);$('player-loop-a').click();await seekRecordingTimeline(.8,false);$('player-loop-b').click();await $('preview').play();});await page.waitForFunction(()=>$('preview').currentTime<.7);await page.evaluate(()=>{$('player-loop-off').click();$('preview').pause();});
page.once('dialog',dialog=>dialog.accept('Chapter one'));await page.evaluate(()=>$('player-bookmark').click());await page.waitForFunction(async()=>!!(await readStore('meta','bookmarks:pro-test'))?.length);assert.match(await page.locator('.player-bookmarks').textContent(),/Chapter one/);
await page.locator('#player-subtitle').setInputFiles({name:'test.srt',mimeType:'text/plain',buffer:Buffer.from('1\n00:00:00,000 --> 00:00:02,000\nTest subtitle\n')});await page.waitForFunction(()=>playerSubtitleTrack?.track.cues?.length===1);await page.evaluate(()=>{$('player-subtitle-offset').value='1';$('player-subtitle-offset').dispatchEvent(new Event('change'));});assert.equal(await page.evaluate(()=>playerSubtitleTrack.track.cues[0].startTime),1);
await page.evaluate(async()=>{audioSelect.value='night';await setPlayerAudio('night');});assert.equal(await page.evaluate(()=>playerAudioGraph.compressor.ratio.value),8);await page.evaluate(async()=>{audioSelect.value='original';await setPlayerAudio('original');});assert.equal(await page.evaluate(()=>playerAudioGraph.compressor.ratio.value),1);assert.equal(await page.evaluate(()=>$('preview').preservesPitch),true);
// Actual writable file handles, using this disposable profile's OPFS for deterministic file IO.
const disk=await page.evaluate(async()=>{captureDirectory=await navigator.storage.getDirectory();const state={name:'disk-test.mp4',session:crypto.randomUUID()},blob=await readStore('videos','pro-test');writeDiskChunk(state,blob.slice(0,100));writeDiskChunk(state,blob.slice(100));await closeDiskSegment(state);const file=await state.diskHandle.getFile();const bytes=new Uint8Array(await file.arrayBuffer()),original=new Uint8Array(await blob.arrayBuffer());return {size:file.size,equal:bytes.every((x,i)=>x===original[i]),stored:state.details.diskName};});assert.ok(disk.equal&&disk.size>100&&disk.stored);
const gains=await page.evaluate(async()=>{const ctx=new AudioContext(),dest=ctx.createMediaStreamDestination(),source=ctx.createOscillator(),volume=ctx.createGain(),sourceDest=ctx.createMediaStreamDestination();volume.gain.value=.2;source.connect(volume).connect(sourceDest);source.start();$('system-gain').value='1';$('capture-limiter').checked=false;configureCaptureAudio(ctx,dest,[sourceDest.stream,null]);mixer=ctx;await ctx.resume();const meter=ctx.createAnalyser();meter.fftSize=2048;ctx.createMediaStreamSource(dest.stream).connect(meter);const buffer=new Float32Array(2048),peak=()=>{meter.getFloatTimeDomainData(buffer);return Math.max(...buffer.map(Math.abs));};await new Promise(r=>setTimeout(r,200));const before=peak();$('system-gain').value='.25';$('system-gain').dispatchEvent(new Event('input'));await new Promise(r=>setTimeout(r,200));const after=peak();source.stop();await ctx.close();mixer=null;return {before,after};});assert.ok(gains.before>.15&&gains.after<gains.before*.4,JSON.stringify(gains));
// Global subtitle times and viewing settings survive a real source switch between parts.
await page.evaluate(async()=>{const first=await readStore('recordings','pro-test'),blob=await readStore('videos','pro-test');await updateRecording(first.id,{recordingGroupId:'pro-group',part:1});const second={...first,id:'pro-part-2',name:'pro-part-002.mp4',recordingGroupId:'pro-group',part:2,createdAt:first.createdAt+4000};await runTx(['recordings','videos'],'readwrite',tx=>{tx.objectStore('recordings').add(second);tx.objectStore('videos').put(blob,second.id);});await playRecording(await readStore('recordings','pro-test'));});await page.waitForFunction(()=>playbackReady&&currentPlayerProject==='pro-group');
await page.locator('#player-subtitle').setInputFiles({name:'parts.srt',mimeType:'text/plain',buffer:Buffer.from('1\n00:00:04,500 --> 00:00:06,000\nSecond part subtitle\n')});await page.waitForFunction(()=>playerSubtitleCues.length===1);await page.evaluate(async()=>{$('preview').volume=.3;$('preview').playbackRate=1.5;setPlaybackRotation(90);await seekRecordingTimeline(5,false);});await page.waitForFunction(()=>playbackReady&&activePlaybackId==='pro-part-2'&&Math.abs($('preview').currentTime-1)<.1);await page.waitForFunction(()=>playerSubtitleTrack?.track.cues?.length===1);assert.equal(await page.evaluate(()=>playerSubtitleTrack.track.cues[0].startTime),.5);assert.equal(await page.evaluate(()=>$('preview').volume),.3);assert.equal(await page.evaluate(()=>$('preview').playbackRate),1.5);assert.equal(await page.evaluate(()=>playbackRotation),90);
// A real independent Opus recorder pauses and resumes together with the main encoder.
const sidecar=await page.evaluate(async()=>{captureDirectory=null;const ctx=new AudioContext(),osc=ctx.createOscillator(),out=ctx.createMediaStreamDestination();osc.connect(out);osc.start();await ctx.resume();displayStream=out.stream;micStream=null;$('capture-tracks').checked=true;startIndependentAudio();recorder=independentTracks[0];activeSegment={awaitingNext:false};pause();const paused=independentTracks.every(e=>e.state==='paused');pause();const resumed=independentTracks.every(e=>e.state==='recording');await new Promise(r=>setTimeout(r,150));stopIndependentAudio();await new Promise(r=>setTimeout(r,300));osc.stop();await ctx.close();recorder=null;displayStream=null;const files=(await readStore('meta')).filter(e=>e?.audioOnly);return {paused,resumed,files:files.length,bytes:files.length?(await loadChunks(files[0].session)).reduce((n,b)=>n+b.size,0):0};});assert.ok(sidecar.paused&&sidecar.resumed&&sidecar.files&&sidecar.bytes>0,JSON.stringify(sidecar));
await page.evaluate(async()=>{await removeRecordings(['pro-test']);await $('library-undo').onclick();});assert.equal(await page.evaluate(async()=>!!(await readStore('recordings','pro-test')).deletedAt),false);assert.deepEqual(errors,[]);console.log(JSON.stringify({frameStep:true,abLoop:true,bookmarksPersist:true,srtAndOffset:true,audioModes:true,pitchPreserved:true,diskBytesPreserved:true,independentGainMeasured:true,undoDeletion:true,crossPartSubtitles:true,viewStateAcrossParts:true,independentAudioPauseSync:true,errors}));
}finally{await context?.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
