// Optional real model integration using an isolated helper and browser profile.
const {chromium}=require('playwright'),fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),http=require('http'),assert=require('assert/strict'),crypto=require('crypto');
(async()=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-face-test-'));let helper,context;
 try{
  const listener=http.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));
  const token=crypto.randomBytes(32).toString('hex');helper=cp.spawn(path.join(root,'enhancement/.venv/bin/python'),[path.join(root,'enhancement/server.py')],{env:{...process.env,WESCREEN_PORT:String(port),WESCREEN_WORK_DIR:path.join(temp,'jobs'),WESCREEN_ENHANCE_TOKEN:token},stdio:['ignore','pipe','pipe']});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Helper startup timeout')),10000);helper.stdout.once('data',()=>{clearTimeout(timer);resolve();});helper.once('exit',code=>{clearTimeout(timer);reject(new Error('Helper exited '+code));});});
  const image=path.join(root,'enhancement/.runtime/codeformer/inputs/cropped_faces/0478.png'),source=path.join(temp,'sample.mp4');
  const generated=cp.spawnSync('ffmpeg',['-v','error','-y','-loop','1','-i',image,'-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','0.5','-r','4','-vf','scale=512:512','-c:v','libx264','-c:a','aac',source]);assert.equal(generated.status,0);
  const bytes=[...fs.readFileSync(source)],hash=crypto.createHash('sha256').update(Buffer.from(bytes)).digest('hex'),version=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'))).version,ext=path.join(temp,'extension');fs.mkdirSync(ext);
  assert.equal(cp.spawnSync('python3',['-c','import zipfile,sys;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',path.join(root,'store',`wescreen-${version}.zip`),ext]).status,0);
  context=await chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,viewport:{width:1440,height:1000},args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`]});
  await context.route('http://127.0.0.1:8765/**',async route=>{const url=new URL(route.request().url()),response=await route.fetch({url:`http://127.0.0.1:${port}${url.pathname}${url.search}`});await route.fulfill({response});});
  const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(30000);await page.goto(`chrome-extension://${new URL(worker.url()).host}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
  await page.evaluate(async({bytes,token})=>{enhancementToken=token;$('enhance-token').value=token;applyLang('zh');const blob=new Blob([new Uint8Array(bytes)],{type:'video/mp4'}),entry={id:'face-original',name:'模型验证样片.mp4',width:512,height:512,duration:500,size:blob.size,createdAt:Date.now()};await runTx(['videos','recordings'],'readwrite',tx=>{tx.objectStore('videos').put(blob,entry.id);tx.objectStore('recordings').put(entry);});await playRecording(entry);},{bytes,token});
  await page.locator('#playback-more-menu > summary').click();await page.locator('#settings-tab-tools').click();await page.locator('#player-face-restore').click();await page.waitForFunction(()=>!enhancementBusy&&helperHealth?.face&&$('enhance-mode').value==='face');assert.equal(await page.locator('#enhance-full').isDisabled(),true);
  await page.locator('#preview-seconds').selectOption('3');await page.locator('#enhance-preview').click();await page.waitForFunction(()=>!enhancementBusy&&facePreviewReceipt);assert.equal(await page.locator('#enhance-full').isDisabled(),true);await page.locator('#face-preview-confirm').check();assert.equal(await page.locator('#enhance-full').isEnabled(),true);
  if(process.env.WESCREEN_FACE_SCREENSHOT)await page.screenshot({path:process.env.WESCREEN_FACE_SCREENSHOT});
  await page.locator('#enhance-full').click();for(let i=0;i<120;i++){if(await page.evaluate(async()=>!enhancementBusy&&(await readStore('recordings')).some(r=>r.enhancement==='face')))break;await page.waitForTimeout(200);}assert.equal(await page.evaluate(async()=>(await readStore('recordings')).some(r=>r.enhancement==='face')),true,await page.locator('#enhance-status').textContent());const result=await page.evaluate(async()=>{const records=await readStore('recordings'),result=records.find(r=>r.enhancement==='face');return {count:records.length,result,original:[...new Uint8Array(await(await readStore('videos','face-original')).arrayBuffer())],output:[...new Uint8Array(await(await readStore('videos',result.id)).arrayBuffer())]};});assert.equal(result.count,2);assert.equal(result.result.enhancedFrom,'face-original');assert.match(result.result.name,/face-generated/);assert.equal(crypto.createHash('sha256').update(Buffer.from(result.original)).digest('hex'),hash);const output=path.join(temp,'output.mp4');fs.writeFileSync(output,Buffer.from(result.output));
  const audio=file=>cp.execFileSync('ffmpeg',['-v','error','-i',file,'-map','0:a:0','-c','copy','-f','adts','pipe:1']);assert.deepEqual(audio(source),audio(output));assert.equal(result.result.width,512);assert.equal(result.result.height,512);
  const blank=path.join(temp,'blank.mp4');cp.execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','color=c=blue:s=160x90:r=4:d=0.5','-c:v','libx264',blank]);const create=await fetch(`http://127.0.0.1:${port}/jobs?mode=face&preview=1&strength=.65`,{method:'POST',headers:{'X-WeScreen-Token':token},body:fs.readFileSync(blank)}),job=await create.json();assert.equal(create.status,202);let info;for(let i=0;i<100;i++){info=await(await fetch(`http://127.0.0.1:${port}/jobs/${job.id}`,{headers:{'X-WeScreen-Token':token}})).json();if(!['queued','processing'].includes(info.state))break;await new Promise(r=>setTimeout(r,200));}assert.equal(info.state,'error');assert.match(info.error,/No usable face/);assert.deepEqual(errors,[]);console.log(JSON.stringify({facePreview:true,confirmedFullSave:true,sourceBytesPreserved:true,sourceAudioPacketsPreserved:true,width:512,height:512,noFaceReportsError:true,errors}));
 }finally{await context?.close();helper?.kill('SIGTERM');if(helper&&helper.exitCode===null)await new Promise(resolve=>{helper.once('exit',resolve);setTimeout(()=>{helper.kill('SIGKILL');resolve();},5000).unref();});fs.rmSync(temp,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
