const {chromium}=require('playwright');const assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
(async()=>{const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-privacy-'));let context;try{
context=await chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,viewport:{width:1440,height:1000},args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`]});await context.route('http://127.0.0.1:8765/**',r=>r.abort());const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const page=await context.newPage(),url=`chrome-extension://${new URL(worker.url()).host}/recorder.html`,errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');await page.evaluate(()=>applyLang('zh'));await page.locator('[data-view=about]').click();await page.locator('#privacy-configure').click();await page.locator('#privacy-password').fill('custom-password-123');await page.locator('#privacy-confirm').fill('custom-password-123');await page.locator('#privacy-submit').click();await page.waitForFunction(()=>!$('privacy-dialog').open);const stored=await page.evaluate(()=>readStore('meta','privacy-password'));assert.equal(stored.iterations,310000);assert.equal(JSON.stringify(stored).includes('custom-password'),false);
await page.locator('[data-view=about]').click();await page.locator('#privacy-configure').click();await page.locator('#privacy-old').fill('custom-password-123');await page.locator('#privacy-password').fill('new-password-456');await page.locator('#privacy-confirm').fill('new-password-456');await page.locator('#privacy-submit').click();await page.waitForFunction(()=>!$('privacy-dialog').open);
const second=await context.newPage();await second.goto(url);await second.waitForFunction(()=>document.documentElement.dataset.ready==='true');await second.locator('[data-view=library]').click();await second.locator('#privacy-password').fill('new-password-456');await second.locator('#privacy-submit').click();await second.waitForFunction(()=>!$('privacy-dialog').open);
await page.locator('[data-view=library]').click();assert.equal(await page.locator('#recording-library').isVisible(),true);await page.locator('#privacy-quick-lock').click();await second.waitForFunction(()=>$('recording-library').classList.contains('hidden'));await second.close();await page.locator('[data-view=library]').click();assert.equal(await page.locator('#privacy-dialog').isVisible(),true);assert.equal(await page.locator('#recording-library').isVisible(),false);await page.locator('#privacy-password').fill('wrong-password');await page.locator('#privacy-submit').click();await page.waitForFunction(()=>$('privacy-error').textContent.length>0);assert.equal(await page.locator('#recording-library').isVisible(),false);await page.locator('#privacy-password').fill('new-password-456');await page.locator('#privacy-submit').click();await page.waitForFunction(()=>!$('privacy-dialog').open);assert.equal(await page.locator('#recording-library').isVisible(),true);
await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');await page.evaluate(()=>applyLang('zh'));await page.locator('[data-view=player]').click();assert.equal(await page.locator('#privacy-dialog').isVisible(),true);await page.screenshot({path:path.resolve(root,'../audit-2026-10-04/privacy-lock.png')});await page.locator('#privacy-cancel').click();assert.equal(await page.locator('#player-view').isVisible(),false);
await page.locator('[data-view=about]').click();await page.locator('#privacy-disable').click();await page.locator('#privacy-password').fill('new-password-456');await page.locator('#privacy-submit').click();await page.waitForFunction(()=>!$('privacy-dialog').open);assert.equal(await page.evaluate(()=>readStore('meta','privacy-password')),undefined);await page.locator('[data-view=player]').click();await page.screenshot({path:path.resolve(root,'../audit-2026-10-04/player-empty-refined.png')});assert.equal(await page.locator('#player-view').isVisible(),true);assert.equal(await page.locator('.workspace-nav').evaluate(el=>getComputedStyle(el).overflowY),'hidden');assert.deepEqual(errors,[]);console.log('Custom password, wrong-password rejection, reload lock, cancel, disable and refined empty state passed');
}finally{await context?.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1)});
