// Validate the exact shipping ZIP in a disposable native-extension profile.
const {chromium}=require('playwright');const fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process');
(async()=>{
 const root=path.resolve(__dirname,'..'),version=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'))).version,zip=path.join(root,'store',`wescreen-${version}.zip`),temp=fs.mkdtempSync(path.join(os.tmpdir(),'wescreen-package-')),unpacked=path.join(temp,'extension');fs.mkdirSync(unpacked);
 const extraction=cp.spawnSync('python3',['-c','import zipfile,sys; zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',zip,unpacked],{encoding:'utf8'});if(extraction.status!==0)throw new Error(extraction.stderr);
 let context;
 try{
  context=await chromium.launchPersistentContext(path.join(temp,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${unpacked}`,`--load-extension=${unpacked}`]});
  await context.route('http://127.0.0.1:8765/**', route=>route.abort());
  const worker=context.serviceWorkers()[0] || await context.waitForEvent('serviceworker'),id=new URL(worker.url()).host,page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
  const iconAlignment=await page.evaluate(()=>[...document.querySelectorAll('.workspace-nav [data-view]')].map(button=>{const icon=button.querySelector('svg.nav-icon').getBoundingClientRect(),label=button.querySelector('[data-i18n]').getBoundingClientRect();return {width:icon.width,height:icon.height,offset:Math.abs(icon.top+icon.height/2-label.top-label.height/2)};}));if(iconAlignment.some(icon=>icon.width!==20 || icon.height!==20 || icon.offset>.5))throw new Error('Navigation icon alignment mismatch');
  const checks=await page.evaluate(async()=>({version:chrome.runtime.getManifest().version,versionBadge:document.querySelector('[data-app-version]').textContent==='v'+chrome.runtime.getManifest().version,unlimitedStorage:await chrome.permissions.contains({permissions:['unlimitedStorage']}),channelWorkbench:!!$('channel-workbench'),rotation:!!$('edit-rotation'),batchQueue:typeof runBatch==='function'}));if(checks.version!==version || Object.values(checks).some(value=>value===false) || errors.length)throw new Error(JSON.stringify({checks,errors}));
  await page.goto(`chrome-extension://${id}/popup.html`);await page.waitForFunction(()=>!document.querySelector('[data-app-version]').hidden);if(await page.locator('[data-app-version]').textContent()!=='v'+version)throw new Error('Popup version mismatch');await page.goto(`chrome-extension://${id}/recorder.html`);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
  if(await page.locator('#course-panel').isVisible())throw new Error('Course recording remains visible');
  if(await page.locator('.github-link').getAttribute('href')!=='https://github.com/susunola/wescreen/releases/latest')throw new Error('Missing download link');
  await page.evaluate(async()=>{await chrome.storage.local.set({settings:{'course-enabled':true,'course-name':'Old course'}});await loadSettings();});
  if(await page.locator('#course-enabled').isChecked())throw new Error('Old course setting changes new recording');
  await page.evaluate(()=>applyLang('zh'));if(process.env.WESCREEN_RECORD_SCREENSHOT)await page.screenshot({path:process.env.WESCREEN_RECORD_SCREENSHOT,fullPage:true});
  for(const lang of ['zh','en']){await page.evaluate(lang=>applyLang(lang),lang);await page.setViewportSize({width:390,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error(lang+' narrow layout overflow');}
  await page.setViewportSize({width:1280,height:800});
  await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const drawing=canvas.getContext('2d');window.testFrames=setInterval(()=>{drawing.fillStyle='blue';drawing.fillRect(0,0,320,180);},33);navigator.mediaDevices.getDisplayMedia=async()=>canvas.captureStream(30);$('preflight-enabled').checked=false;$('countdown').value='0';$('screen-audio').checked=false;$('clicks').checked=false;await start();});
  await page.waitForTimeout(1200);const control=await context.newPage();await control.goto(`chrome-extension://${id}/controls.html`);await control.waitForFunction(()=>!document.getElementById('pause').disabled);await control.locator('#pause').click();await page.waitForFunction(()=>recorder.state==='paused');await control.locator('#pause').click();await page.waitForFunction(()=>recorder.state==='recording');await control.locator('#stop').click();await page.waitForFunction(()=>recorder===null && finalId);await page.waitForFunction(()=>$('review-frames').children.length===3);checks.controlRouting=true;await control.close();
  if(!await page.locator('#result').isVisible())throw new Error('Recording completion page missing');await page.locator('#result-play').click();if(!await page.locator('#player-view').isVisible())throw new Error('Play now did not enter player');
  const savedId=await page.evaluate(()=>finalId);await page.locator('[data-view=library]').click();await page.locator('[data-view=capture]').click();if(!await page.locator('#setup').isVisible())throw new Error('Recording menu stays on result');if(!await page.evaluate(async id=>!!(await readStore('recordings',id)),savedId))throw new Error('Returning to setup removed saved recording');
  await page.evaluate(()=>show('result'));await page.locator('#new-recording').click();if(!await page.locator('#setup').isVisible())throw new Error('Next recording failed');checks.nextRecordingNavigation=true;
  await context.unroute('http://127.0.0.1:8765/**');
  await context.route('http://127.0.0.1:8765/**',route=>{const url=new URL(route.request().url());return route.fulfill({json:url.pathname==='/connect' ? {token:'test-credential-for-isolated-check'} : url.pathname==='/health' ? {ready:true,ai:true,strong:true} : {jobs:[]}});});
  await page.evaluate(async()=>{await connectHelper();navigateWorkspace('tasks');await renderEnhancementTasks();});
  if(!await page.locator('#tasks-empty').isVisible() || await page.locator('#tasks-connect').isVisible())throw new Error('Connected empty processing state incorrect');
  await page.locator('#tasks-library').click();if(!await page.locator('#recording-library').isVisible())throw new Error('Empty-state library action failed');
  await page.locator('[data-view=tasks]').click();await page.evaluate(()=>applyLang('zh'));
  if(process.env.WESCREEN_UI_SCREENSHOT){await context.route('http://127.0.0.1:8765/**',route=>{const u=new URL(route.request().url());return route.fulfill({json:u.pathname==='/jobs' ? {jobs:[{id:'design-demo-active',name:'Telegram-channel-001.mp4',mode:'ai',state:'processing',progress:.64,createdAt:Date.now()},{id:'design-demo-done',name:'City-walk-1080p.mp4',mode:'natural',state:'done',size:44000000,createdAt:Date.now()-1000}]}:u.pathname==='/health' ? {ready:true,ai:true,strong:true}:{token:'test-credential-for-isolated-check'}});});await page.evaluate(()=>renderEnhancementTasks());await page.screenshot({path:process.env.WESCREEN_UI_SCREENSHOT,fullPage:true});await context.unroute('http://127.0.0.1:8765/**');await context.route('http://127.0.0.1:8765/**',route=>{const u=new URL(route.request().url());return route.fulfill({json:u.pathname==='/connect' ? {token:'test-credential-for-isolated-check'}:u.pathname==='/health' ? {ready:true,ai:true,strong:true}:{jobs:[]}});});await page.evaluate(()=>renderEnhancementTasks());}
  for(const lang of ['zh','en']){await page.evaluate(lang=>applyLang(lang),lang);await page.setViewportSize({width:390,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Processing narrow overflow '+lang);}
  await page.waitForFunction(()=>!taskPolling && !helperConnecting);
  await context.unroute('http://127.0.0.1:8765/**');await context.route('http://127.0.0.1:8765/**',route=>route.abort());
  await page.evaluate(async()=>{await renderEnhancementTasks();});await page.waitForFunction(()=>!document.getElementById('tasks-connect').hidden);if(!await page.locator('#tasks-connect').isVisible())throw new Error('Offline reconnect action missing');
  checks.processingEmptyState=true;checks.processingConnectionStatus=true;

  await page.setViewportSize({width:1280,height:1000});await page.evaluate(()=>applyLang('zh'));
  await page.locator('[data-view=about]').click();if(!await page.locator('#about-view').isVisible())throw new Error('About navigation failed');
  if(!await page.locator('#about-view').textContent().then(text=>text.includes('atomoswang')))throw new Error('About author missing');
  if(await page.locator('#about-view [data-app-version]').textContent()!=='v'+version)throw new Error('About version mismatch');
  if(await page.locator('#about-helper-download').getAttribute('href')!=='https://github.com/susunola/wescreen/releases/latest')throw new Error('Helper download link missing');
  if(process.env.WESCREEN_ABOUT_SCREENSHOT)await page.screenshot({path:process.env.WESCREEN_ABOUT_SCREENSHOT,fullPage:true});
  await page.evaluate(async()=>{const original=await readStore('recordings',finalId),blob=await readStore('videos',finalId);await updateRecording(original.id,{sourceTitle:'视频演示'});const child={...original,id:crypto.randomUUID(),name:'demo-natural.mp4',enhancedFrom:original.id,enhancement:'natural',createdAt:Date.now()};await runTx(['recordings','videos'],'readwrite',tx=>{tx.objectStore('recordings').put(child);tx.objectStore('videos').put(blob,child.id);});librarySelection.add(child.id);await renderRecordingLibrary();navigateWorkspace('library');});
  if(await page.locator('.media-row').count()!==2 || await page.locator('.derived-row').count()!==1)throw new Error('Library version grouping failed');
  await page.locator('.row-menu summary').first().click();await page.evaluate(async()=>{await saveThumbnail(await readStore('videos',finalId),finalId);});if(!await page.locator('.row-menu').first().getAttribute('open').then(value=>value!==null))throw new Error('Thumbnail refresh closed recording actions');await page.locator('.row-menu summary').first().click();
  await page.locator('.library-more-filters summary').click();await page.locator('#library-kind').selectOption('enhanced');await page.waitForFunction(()=>document.querySelectorAll('.media-row').length===1);if(await page.locator('.derived-row').count()!==1)throw new Error('Enhanced version filter failed');await page.locator('#library-kind').selectOption('original');await page.waitForFunction(()=>document.querySelectorAll('.media-row').length===1 && !document.querySelector('.derived-row'));await page.locator('#library-kind').selectOption('');await page.waitForFunction(()=>document.querySelectorAll('.media-row').length===2);await page.locator('.library-more-filters summary').click();
  if(process.env.WESCREEN_LIBRARY_SCREENSHOT)await page.screenshot({path:process.env.WESCREEN_LIBRARY_SCREENSHOT,fullPage:true});
  for(const lang of ['zh','en']){await page.evaluate(lang=>applyLang(lang),lang);await page.setViewportSize({width:390,height:844});for(const view of ['library','about']){await page.evaluate(view=>navigateWorkspace(view),view);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error(view+' narrow overflow '+lang);}}
  checks.aboutPage=true;checks.libraryRedesign=true;
  await page.setViewportSize({width:1280,height:1000});await page.evaluate(()=>applyLang('zh'));
  await page.evaluate(async()=>{const profile={id:'design-channel',name:'摄影学习',url:'https://t.me/example',channelProfile:true,nextEpisode:3,exportFolder:'WeScreen/Telegram/摄影学习',plan:[{id:'sample-one',title:'光线与曝光',url:'https://t.me/example/1'},{id:'sample-two',title:'镜头运动',url:'https://t.me/example/2',status:'skipped'},{id:'sample-three',title:'构图基础',url:'https://t.me/example/3'}]};await runTx('meta','readwrite',tx=>tx.objectStore('meta').put(profile,'channel:'+profile.id));await updateRecording(finalId,{channelTaskId:'sample-one'});await loadTelegramProfiles(profile.id);fillChannel(chosenChannel());$('channel-plan-item').value='sample-three';$('channel-plan-item').dispatchEvent(new Event('change'));navigateWorkspace('channels');await renderChannelWorkbench();});
  if(await page.locator('[data-view]').count()!==6)throw new Error('Expected six peer tabs');
  if(!await page.locator('.channel-plan-row.selected').textContent().then(text=>text.includes('构图基础')))throw new Error('Selected video missing');
  if(process.env.WESCREEN_TELEGRAM_SCREENSHOT)await page.screenshot({path:process.env.WESCREEN_TELEGRAM_SCREENSHOT,fullPage:true});
  await page.locator('#channel-add-video').click();if(!await page.locator('#channel-plan-dialog').isVisible())throw new Error('Plan editor did not open');await page.locator('#channel-plan-close').click();
  page.once('dialog',dialog=>dialog.accept());await page.locator('#channel-clear-completed').click();await page.waitForFunction(()=>document.querySelectorAll('#channel-plan-rows>li').length===2);if(!await page.evaluate(async()=>!!(await readStore('recordings',finalId))))throw new Error('Clearing completed plan removed video');
  for(const lang of ['zh','en']){await page.evaluate(lang=>applyLang(lang),lang);await page.setViewportSize({width:390,height:844});for(const view of ['channels','capture']){await page.evaluate(view=>{navigateWorkspace(view);if(view==='capture')show('setup');},view);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error(view+' redesign narrow overflow '+lang);}}
  checks.recordingRedesign=true;checks.telegramRedesign=true;
  console.log(JSON.stringify({package:path.basename(zip),...checks,errors,narrowLanguages:['zh','en']}));
 }finally{if(context)await context.close();fs.rmSync(temp,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
